### ISSUE TITLE
Durchwahlen bei team

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#100]
Momentan kann man bei team per `<Dial><Number>11</Number></Dial>` anscheinend nicht die interne Durchwahl "11" anwählen (Ansage: "ungültige Rufnummer").

Das wäre aber gut, insbesondere für DTMF etc. sipgate.io sollte also auch Durchwahlen unterstützen.

**Comment by CookieCrumb23** [comment]
Entschuldige, dass es etwas gedauert hat, aber das Problem sollte jetzt behoben sein.
