### ISSUE TITLE
Anonyme Anrufer ablehnen/ Blockieren

### ISSUE THREAD

**Issue by beyondder** [sipgate/sipgate.io#102]
Wie kann man am besten Anonyme Anrufer ablehnen/ Blockieren?

Ich dachte an einer Lösung alla: "Conditional" nach dem Motto:

**If Number suppressed  > Then Block Number** 

oder am besten 

**If Number suppressed  > Then Mp3Voice**

Ggf. eine Sprach Datei mit der Meldung: "Anonyme Anrufer werden leider abgelehnt, bitte versuchen Sie es erneut" 

oder so in der Art...

Was haltet Ihr von der Grundidee?

**Comment by danielberlin** [comment]
Das geht problemlos. Wenn ein Push mit `from=anonymous` (Auswertung von `$_POST['from]` und sonst https://github.com/sipgate/sipgate.io/blob/master/examples/php/play_url.php) eingeht, antwortest Du mit:

```
<Response>
   <Reject />
</Response>
```

bzw:

```
<Response>
    <Play>
        <Url>http://example.com/bitte-ohne-rufnummernunterdrueckung-erneut-anrufen.wav</Url>
        <Voicemail />
    </Play>
</Response>
```

Die Logik (" Lösung alla: "Conditional") liegt damit nicht innerhalb der Response, sondern du wertest den Push aus und reagierst entsprechend mit der passenden Response.
