### ISSUE TITLE
Absendernummer für ausgehende SMS setzen

### ISSUE THREAD

**Issue by andreas1288** [sipgate/sipgate.io#113]
Die Steuerungsmöglichkeiten für Anrufe sind sehr vielfältig und funktionieren sehr zuverlässig. Vielen Dank dafür!

Leider fehlt die Steuerung der SMS vollständig. Ich kann verstehen, dass wegen gesetzlicher Einschränkungen vieles nicht geht. Es wäre jedoch sehr sehr hilfreich, wenn man die Absendernummer für ausgehende SMS einstellen könnte. Das geht bisher nur über das WEB-Interface. Nicht über die offizielle API. (Oder ich bin einfach zu blind, den Aufruf zu finden ;-) Alles andere kann das Handy auch selbst machen, nur das halt nicht.

Vielen Dank!

**Comment by derveloper** [comment]
Hallo andreas1288,

die Absenderrufnummer einer SMS kannst Du hier setzen: https://api.sipgate.com/doc/#!/sms/addCallerId

Grüße,
Tristan

**Comment by derveloper** [comment]
Ich gehe davon aus das dein Problem erstmal gelöst ist. Daher mache ich diese Issue ertsmal zu.
