### ISSUE TITLE
Direkt mit HTTP-Auth pushen und zur Effizienz 401er-POST vermeiden

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#114]
Ich habe die API-Skripte per HTTP Auth geschützt und entsprechend https://htuser:htpass@myserver/ioscript als Push-URL eingetragen. Jetzt bin ich am Optimieren, da es tageszeit- und lastabhängig einige Pushs gibt, die nicht durchkommen (500 Internal Server Error oder 600 IO Error) und ich auch nicht genau weiß, ob der Flaschenhals bei mir oder auf Push-Seite ist.

Momentan sehe ich im Server-Log für jeden einzelnen Push zwei POST-Requests, zuerst einen, der von meinem Server mit 401 ("Authorization required") beantwortet wird, und dann direkt im Anschluss einen mit 200, der den eigentlichen Push enthält.

Wenn ich mit

`curl -A "sipgate.io" -X POST --data $POST "https://htuser:htpass@myserver/ioscript" -D -`

pushe, erhalte ich nur den 200er POST-Request ohne vorangehenden 401er.

D.h. man könnte 50% der HTTP-Verbindungen einsparen, wenn man bei Vorhandensein eines "@" im Feld Push-URL direkt entsprechend pushen würde, so wie es curl macht, anstatt ohne `htuser:htpass@`zu pushen. Ein Browser macht es so, aber der muss dem Benutzer ja auch das Loginfenster präsentieren. Der Push sollte so effizient wie möglich sein und das Passwort direkt mitpushen.

**Comment by spcontent** [comment]
Kurze Rückfrage an Daniel, wird hier überhaupt noch aktiv betreut von Sipgate?

**Comment by fuglu** [comment]
Wir würden `Preemptive Authentication` ungern erlauben. Wir orientieren uns da am Standardverhalten von Chrome, Firefox und unserem HTTP Client. Curl scheint offensichtlich standardmäßig Preemptive Authentication zu machen.
