### ISSUE TITLE
CallId unterschiedliche

### ISSUE THREAD

**Issue by bagsik** [sipgate/sipgate.io#119]
Die CallId aus dem Webhook und die aus dem RTCM sind unterschiedlich.

**Comment by fuglu** [comment]
Tatsächlich funktionieren beide CallId. Dass die API an dieser Stelle inkonsistent ist, sollte natürlich nicht so sein. Wir schauen uns das voraussichtlich heute an. Vielen Dank für's Reporten :+1:

**Comment by fuglu** [comment]
Wir haben uns das Problem angeschaut, konnten es aber nicht auf die Schnelle lösen. Wir bleiben dran.

**Comment by gidsi** [comment]
Bugfix wurde heute Morgen eingespielt, jetzt sollte die CallId über alle Wege immer gleich sein.

Danke fürs Bescheid geben :)

**Comment by bagsik** [comment]
Sieht gut aus

Kriegt ihr die CallId vielleicht auch noch in die Call History mit rein?

**Comment by gidsi** [comment]
Jupp, das haben wir schon auf der ToDo Liste :)
