### ISSUE TITLE
Mehrere POST Requests für unterschiedliche Events

### ISSUE THREAD

**Issue by fuglu** [sipgate/sipgate.io#12]
@mdsoft #1:

Noch ein Vorschlag zum Ausbau der API.
Eierlegende Wollmichsäue sollen ja selten sein, aber einen Versuch eines zu skizzieren erlaube ich mir trotzdem ;-)
Für eine möglichst universelle Nutzbarkeit der sipgate POST API wäre es optimal, wenn die API für alle auftretenden Ereignisse ein POST senden würde. Folgend ein Vorschlag für mögliche Parameter und deren Ausprägung.

    timestamp
    event_id
    event: call|ring|connect|disconnect|busy|divert|sms|voicemail
    to
    from
    content: sms|voicemail (Abschrift)
    duration
    cost

Aus diesen umfangreichen Daten könnte ein Empfänger die von ihm benötigten Informationen auslesen und entsprechend verarbeiten. Mit diesen umfangreichen Informationen sollten sich viele denkbare Szenarien umsetzen lassen. Zum Beispiel ein selbst geführter EVN oder Anrufinfo bei Besetzt oder ...

**Comment by danielberlin** [comment]
+1

**Comment by danielberlin** [comment]
Siehe auch #20 

`from=492111234567&to=4915791234567&direction=in&status=reachable`

Conditionality
------

Parameter | Description
--------- | -----------
unreachable      | mobile phone is not reachable (off or out of network range)
busy        | mobile phone is busy
reachable | mobile phone is on

Dann könnte man anhängig vom aktuellen Status der SIM entscheiden, was mit dem Anruf geschieht. Ohne Erweiterung der GET-Parameter könnte man immerhin allgemeiner festlegen, dass z.B. Anrufe von bestimmten Anrufern nur dann weitergeleitet oder abgewiesen werden, wenn das Handy in einem bestimmten Zustand (z.B. unreachable) ist.

Details siehe #20

**Comment by findingmarbles** [comment]
Den ursprünglichen Vorschlag von @fuglu haben wir angefangen umzusetzen mit dem answer- und hangup-Events. Von den Anfragen, die uns direkt erreichen, deckt das die Anforderungen der allermeisten Kunden bereits ab. 
(Uns ist nicht klar, ob die +1 sich auf das ursprüngliche beziehen, oder @27o s Rufumleitungskommentar.)

Falls jetzt noch ganz dringend etwas fehlt, bitten wir um eine neue Issue. Danke.
