### ISSUE TITLE
Improved field description

### ISSUE THREAD

**Issue by sieppl** [sipgate/sipgate.io#120]
I was missing from the documenation an overview what values are possible for example for "cause" and in general what type and length to be expected. At the moment developeres have to guess how long a callId can become. 
Can you please update the readme?

**Comment by AlphaBetaPeter** [comment]
Hey @sieppl 
The possible causes (e.g. for hangup) are listed in the readme already: 
https://github.com/sipgate/sipgate.io#hangup-causes
To be up to date we recommend our new developer portal where you can find the causes as well:
https://developer.sipgate.io/v1.0/reference#hangup-causes-1
The type of these causes will always be a string. 

The callIds are variable in length as of now. To be safe i would recommend a length of at least 200 characters or a variable length if possible. Please note that the length and form of a callId might change in the future.

**Comment by sieppl** [comment]
Hi, 

I was also asking for a better description of **every** field content, e.g. "string, length 200 chars" etc.
This should be in the readme!

Kind regards
Sebastian

**Comment by AlphaBetaPeter** [comment]
Alright. Thanks for the clarification. As we are continuously improving our documentation we certainly will  take this into consideration.

Regards
Peter
