### ISSUE TITLE
sipgate.io URLs

### ISSUE THREAD

**Issue by DaSpors** [sipgate/sipgate.io#121]
Mit https://api.sipgate.com/v1/settings/sipgateio können laut Dokumentation die callback URLs gelesen/gesetzt werden. 
Leider sind dies nicht dieselben wie die, die im normalen (Endbenutzer) Userinterface eingestellt werden können.

Werden beide Paare Callbacks ausgelöst?

**Comment by FreakyBoy** [comment]
Hey, 
mit einem neuen Anruf wird die URL aufgerufen die du in dem "Userinterface" eingetragen hast "URL für eingehende Telefonate:". Und nun entscheidet deine Logik hinter der URL was passieren soll. Du hast die möglichtkeit mit dem "onAnswer" und "onHangup", in der XML Response von der ersten URL, die URL zu setzen bzw. kannst du damit auch die "onHangup" URL die im  Userinterface eingetragen ist zu überschreiben.

So meine erfahrung mit der API

**Comment by DaSpors** [comment]
@FreakyBoy Das ist mir klar und das ist nicht Gegenstand der Frage.
Es geht darum, via REST API die "URL für eingehende Telefonate" zu ändern. Das geht und das funktioniert, aber es scheint unabhängig von der Einstellung in Userinterface zu sein.

Hintergrund: Wir haben eine App, die bisher auf eine Einstellung der User angewiesen war (eben im Userinterface). Jetzt haben wir die REST API angebunden und setzen die URLs selbst, aber u.U. müssen die Bestandskunden die URLs manuell wieder im Userinterface entfernen.

**Comment by BlackMac** [comment]
@DaSpors `/v1/settings/sipgateio` gewinnt. Wenn der Kunde also über das Webinterface die URLs gesetzt hat werden diese zwar nicht gelöscht oder überschrieben, aber auch nicht mehr aufgerufen. Die über die API gesetzten URLs habe vorrang.
