### ISSUE TITLE
deviceId wird bei Start neuer Session ignoriert

### ISSUE THREAD

**Issue by Cruiser13** [sipgate/sipgate.io#124]
Hallo zusammen,
unsere Mitarbeiter starten aus unserem CRM Anrufe an Personen über Ihre Geräte, dafür verwenden wir die API: https://developer.sipgate.io/reference#sessions

Aufruf sieht also in etwa so aus:
`curl --request POST \
  --url https://api.sipgate.com/v1/sessions/calls \
  --data '{"deviceId":"e4","caller":"p0","callee":"+49123456789"}'`

Leider wird die deviceId bei uns komplett ignoriert, der Anruf wird stets auf allen Geräten des Mitarbeiters (z.B. Handy mit Sipgate SIM und Softphone) gestartet.

Lässt sich das beheben?

**Comment by bfncs** [comment]
Hallo,

das von dir beschriebene Problem hängt nicht mit der Push API hier im Repository, sondern mit unserer REST-API zusammen. Bitte melde dich mit dem Beispiel und deiner Kundennummer bei unserem Support unter [support@sipgate.io](support@sipgate.io), dann helfen wir dir weiter.
