### ISSUE TITLE
Eingehende und ausgehende Webhook URLs

### ISSUE THREAD

**Issue by nickw108** [sipgate/sipgate.io#125]
Im README zeigt der Link für "Enter an URL for incoming/outgoing calls in the dashboard" auf https://app.sipgate.com/w0/connections/phonelines/p0/dialog/sipgate-io-url/incoming, welcher eine weisse Seite zeigt. Wäre nett, wenn man den korrigieren könnte.

Ich habe eine ausgehende URL von Slack hinterlegt, bei einem Anruf sehe ich aber weder in Slack etwas, noch finde ich einen Event im aktivierten Debug-Log.

**Comment by jmens** [comment]
Die Webhooks Konfiguration haben eine neue Seite bekommen - https://console.sipgate.com. 
Die beiden Links in der README sind aktualisiert - danke für den Hinweis!
