### ISSUE TITLE
Voraussetzungen für Webhooks mit Gather and Play?

### ISSUE THREAD

**Issue by SBejga** [sipgate/sipgate.io#126]
Hi,

auf der Suche nach einer Telefon API bin ich bei Sipgate.io gelandet, was an sich sehr vielversprechend klingt.

Ich bin auf der Suche nach einer API, wo die Nutzer anrufen (oder angerufen werden) und Zahlen eingeben sollen (Ankunftszeit in Minuten). Bei meinen ersten Versuchen mit der Webhook API, klappt das leider nicht. 

Die Anrufe tauchen an meiner API auf und ich sehe eine korrekte XML Response in der sipgate.io Console. Aber wenn ich `Gather` oder `Play` als XML Response schicke passiert nichts. Ich erhalte immer nur die Ansage "Gesprächspartner nicht erreichbar". Kein Ton, keine Eingabe. 

Ich habe testweise einmal eine Response mit Voicemail gesendet. Da wird der Anruf dann korrekt auf die Voicemail umgeleitet. Aber ich möchte ja eine Dateneingabe bevor der Anruf weitergeleitet wird.

Muss denn ein Sipgate Client verbunden sein, damit es funktioniert? 
Ich probiere es mit einem Sipgate basic account.

**Comment by BlackMac** [comment]
Hallo!

Kannst du bitte eine Mail an stefan@sipgate.io schreiben? Da können wir die bestimmt besser helfen und auch in deinen Account schauen.

**Comment by SBejga** [comment]
Hi @BlackMac, sehr gerne! 

Kurz nach meinem issue hier, habe ich auch die sipgate.io Begrüßungs-Mail bekommen und habe auf diese geantwortet. Es müsste jetzt in support ticket geben.

Besten Dank

**Comment by YogeshMahera-SerpentCS** [comment]
@SBejga Could you please guide me how it will be work? I have same issue 
>The calls appear on my API and I see a correct XML response in the sipgate.io console. But if I send Gatheror Playas an XML response nothing happens. I always receive only the announcement "Interlocutor unavailable". No sound, no input.
