### ISSUE TITLE
Kein Answer-Event bei Pickup

### ISSUE THREAD

**Issue by maxnowack** [sipgate/sipgate.io#127]
Wir haben festgestellt, dass kein Answer-Event geschickt wird, wenn ein Gespräch von einem anderen User über `*9` geholt wird. Lediglich das Hangup-Event wird gesendet, sobald das Gespräch beendet wurde.

**Comment by AlphaBetaPeter** [comment]
Hallo @maxnowack,
wir schicken nun auch ein Answer-Event bei einem Pickup raus. 
Der User, der den Anruf geholt hat, steht nicht im Event. Das werden wir uns bei Zeiten noch einmal angucken.

**Comment by maxnowack** [comment]
@AlphaBetaPeter das wäre super, denn ohne die userId ist das Issue für uns leider nur teilweise behoben, da wir den weiteren Gesprächsablauf nicht mit tracken können
