### ISSUE TITLE
Komplexere (Nested) Aktionen (mit Play und/oder Gather)

### ISSUE THREAD

**Issue by smb** [sipgate/sipgate.io#129]
Es sollte möglich sein, nach einer <Response>/<Play> Aktion noch weitere Aktionen auszuführen (Dial, Gather, Reject, Hangup) - so dass ein Soundfile zum Beispiel auch als "Ablehnungs"-Grund genutzt werden kann.

```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Play>
        <Url>http://example.com/example.wav</Url>
    </Play>
    <Reject reason="busy" />
</Response>

```

Konkrete Beispiele:

1. Prüfung Anrufer (Code-Eingabe mit Gather) - Ansage, dass Code nicht korrekt ist mit Play und dann Reject/Hangup
2. Prüfung Zeitraum (Erkennung Arbeitstag oder ggf. sogar Anwesenheit einzelner Personen über Kalender) und Umleitung an andere Nummer (oder Voicebox) oder sogar Reject nach eigener Ansage mit Play

**Comment by bfncs** [comment]
Um komplexere, mehrschrittige Interaktionen umzusetzen, kannst mit der `callId` aus dem Push-Request zu jeder Zeit im laufenden Call unsere [RTCM-API](https://developer.sipgate.io/rest-api/rtcm/) benutzen. Damit kannst du alle von dir beschriebenen Szenarien umsetzen.

**Comment by smb** [comment]
Danke! Hatte die Verbindung zur REST / RTCM übersehen.

Was mir beim Durchschauen der REST API aufgefallen ist:

Ich habe ja die Möglichkeit Telefone ohne Benutzer anzulegen (so würde ich wahrscheinlich Service-Hotlines realisieren, da hier ja kein Benutzer notwendig ist sondern alles über API gesteuert und an eine (oder mehrere) Zielnummern weitergeleitet wird).

Leider kann man anscheinend über die REST API nicht auf diese Devices Zugreifen (Forwardings nur über Userid/Phoneline/Device möglich). Ist das beabsichtigt oder ist hier eine Änderung er API möglich?
