### ISSUE TITLE
Fehlende Dokumentation von `origCallId` und `xcid`

### ISSUE THREAD

**Issue by olivermg** [sipgate/sipgate.io#136]
Das Feld `origCallId` wird leider nicht in der Dokumentation erwähnt: https://developer.sipgate.io/push-api/api-reference/ . Da es sich doch um ein recht wichtiges Feld handelt, mit dem man nachvollziehen kann, ob ein Call eine Relation zu einem vorherigen Call besitzt (z.B. eine Weiterleitung) wäre es sicherlich hilfreich, wenn es dokumentiert wäre.

Gleiches gilt für `xcid`, das ein relativ neues Feld zu sein scheint. Meine Vermutung ist, dass es einen "Callflow" (ursprünglicher Call -> Weiterleitungscall -> ...) identifiziert, aber ohne Dokumentation bleibt das nur eine Vermutung.

Ich würde erwarten, dass sowohl `origCallId` als auch `xcid` dokumentiert sind.

**Comment by dennisoderwald** [comment]
+1

**Comment by l00kuss** [comment]
origCallId und xcid sind eingebaut, siehe: https://developer.sipgate.io/push-api/api-reference/
