### ISSUE TITLE
Möglichkeit auf DTMF reagieren

### ISSUE THREAD

**Issue by Dtrieb** [sipgate/sipgate.io#18]
Schön wäre es, wenn man die Nummer anrufen kann und dann DTMF Töne auswerten kann.
So könnte man ein Menü, etc. programmieren.

**Comment by askeron** [comment]
Hi, leider konnte ich sipgate.io noch nicht ausprobieren, da es für basic Kunden ja noch nicht zur Verfügung steht. Passiert mit sipgate.io wirklich alles vor dem Annehmen des Anrufes?

Ich fände nämlich auch die Möglichkeit super auf DTMF Töne zu reagieren um virtuelle Sprachcomputer zu bauen. Ich hätte da viele realistische Einsatzmöglichkeiten. Meine Vorstellung wäre, dass jemand die Telefonnummer anruft, sipgate einen Request verschickt und ich daraufhin als Response etwas folgendes schicke:

```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Play>
        <Url>http://example.com/example.wav</Url>
    </Play>
    <WaitForDTMF/>
</Response>
```

Der Anrufer würde die Wave-Datei hören und dann per DTMF etwas auswählen. Darauf hin würde sipgate wieder einen Request schicken, wobei ein Parameter DTMF mit der Eingabe des Anrufer mitgeliefert würde, auf den dann wieder reagiert werden kann.

Weitere schöne Verbesserungen wäre dabei:
* Statt der Wave-Datei kann eine Text angegeben werden, der mittels Sprachausgabe umgewandelt wird (bereits anderes Issue).
* Es gibt statt <WaitForDTMF/> auch ein <WaitForSound/> und im nächsten Request erhält man nicht die DTMF-Eingabe, sondern den Link zu einem Soundfile.
* Es gibt eine eindeutige CallId pro Anruf zur guten Zuordnung.

Praktische Anwendungsbeispiele:
* Einfaches Abstimmungssystem
* Sprachcomputer für die Supporthotline eines kleinen Unternehmens
* Sprachcomputer für Heimautomatisierungen (alles im Smart Home einfach übers Telefon steuern)
* ...

**Comment by jumoog** [comment]
Wie ist der Status?

**Comment by danielberlin** [comment]
DTMF ist jetzt möglich per <Gather>.

https://github.com/sipgate/sipgate.io/commit/715ac9c26791476efb71adaa4f4377d4cc3c225b

**Comment by askeron** [comment]
Sehr cool, darauf warte ich schon lange. Werde ich direkt mal ausprobieren.

**Comment by wiesson** [comment]
@askeron [Hier](https://www.youtube.com/watch?v=oSsDNwcZqEU) noch ein kurzes Beispiel, was man mit DTMF noch so machen kann ;)
