### ISSUE TITLE
Call log

### ISSUE THREAD

**Issue by silsha** [sipgate/sipgate.io#2]
Eine Möglichkeit die bisherige Anrufsliste bis zu einem bestimmten Timestamp herunterzuladen wäre großartig.

Ich hatte da mal angefangen was in Node.js zu basteln, was die Daten aus den EVNs lädt. Eher schlecht als recht. https://github.com/silsha/simquadrat.js/tree/master

**Comment by wiesson** [comment]
Du kannst die Eventliste / Calllog ebenfalls über unsere [XML RPC Api](http://www.sipgate.de/team/faq/article/434/Was_ist_die_sipgate_API_und_welche_Funktionen_bietet_sie) abrufen, anstatt die Seite auszulesen. Sofern sipgate.io in Zukunft eine eigene Möglichkeit bereitstellen wird, kündigen wir das natürlich über den Blog / Twitter / Newsletter an.
