### ISSUE TITLE
XML response "SMS"

### ISSUE THREAD

**Issue by 7270bs** [sipgate/sipgate.io#20]
Vorschlag zur Erweiterung der API:

Eine neue XML response "SMS" einführen - Versand einer SMS (zu den bekannten Tarifen).

Dem bereits existierenden Issue https://github.com/sipgate/sipgate.io/issues/12 schließe ich mich insoweit an, alsdaß es wünschenswert wäre, fürs Erste wenigstens auch einen neuen POST-Request für eingehende SMS zu schaffen ( nur, wenn Handset eingebucht - wie bei https://www.simquadrat.de/feature-store/sms-to-mail ).

**Comment by danielberlin** [comment]
Zu "nur, wenn Handset eingebucht - wie bei https://www.simquadrat.de/feature-store/sms-to-mail )" wäre es gut, wenn man beim XML-Response eine fallabhängige Aktion angeben könnte.

Z.B. ein `Reject` per `if` nur dann, wenn das Handy nicht im Netz eingebucht ist. Oder auf die Voicemail nur dann, wenn gerade ein Gespräch geführt oder das Handy eingebucht ist, damit bei abgeschaltetem Handy der Anrufer ein `Reject` erhält und sofort weiß, dass er nochmal anrufen soll, wenn das Handy eingeschaltet ist (z.B. nachts oder wenn man im Kino/Konzert ist, da will man dann am nächsten Tag nicht zig Voicemail-Anrufe durchgehen müssen, sondern wessen Anliegen dann noch weiter akut und wichtig ist, der wird erneut anrufen).

Conditionality
------

Parameter | Description
--------- | -----------
unreachable      | mobile phone is not reachable (off or out of network range)
busy        | mobile phone is busy
reachable | mobile phone is on

**Example 1: Reject call conditionally if mobile phone is not reachable (off, out of network range)**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
	<Reject if="unreachable" />
</Response>
```

**Example 2: Reject call conditionally if mobile phone is busy (active call)**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
	<Reject if="busy" />
</Response>
```

**Example 3: Reject call conditionally if mobile phone is not reachable (off, out of network range)**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial if="reachable">
        <Voicemail />
    </Dial>
</Response>
```

Diese Beispiele würden auch ohne Erweiterung der GET-Parameter funktionieren und das wäre wohl einfacher zu implementieren. Grundsätzlich wäre jedoch ein zusätzlicher GET-Parameter sehr praktisch und sinnvoll, der bereits den Status der SQ-SIM übermittelt. D.h. wenn ein eingehender Anruf über sipgate.io signalisiert wird, muss ermittelt werden, ob die SQ-SIM eingebucht ist.

`from=492111234567&to=4915791234567&direction=in&status=reachable`

**Comment by CookieCrumb23** [comment]
SMS Versand über sipgate.io ist etwas was wir durchaus im Auge haben, aber in absehbarer Zeit werden wir es wohl erstmal nicht angehen.
