### ISSUE TITLE
Erweiterung Play um sofortigen Rufaufbau während soundfile noch spielt

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#22]
Die Option Play sollte derart erweitert werden, das per zusätzlichem Parameter auswählbar ist, die im Anschluss an das vollständige Abspielen des Soundfiles durchzuführende Aktion (i.d.R. Anruf des SQ-Teilnehmers) bereits während des Abspielens zu starten. Beispiel:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Play next="immediately">
        <Url>http://example.com/example.wav</Url>
    </Play>
</Response>
```

Attribute | Possible values | Default value
--- | --- | ---
next | sequently, immediately | sequently

Der Anrufer würde also unmittelbar ohne Freizeichen eine Wartemelodie hören, währenddessen ("immediately") bereits der Rufaufbau zur SIM erfolgt, der bislang ("sequently") erst nach Beendigung des Soundfiles passieren würde. Da der Rufaufbau im Mobilfunknetz sowieso generell einige wenige Sekunden in Anspruch nimmt, kann so bei einem nicht allzu langen Soundfile ein praktischer Wartemelodieeffekt erzielt werden.

**Comment by danielberlin** [comment]
Das wäre schon vielseitig einsetzbar, als Freizeichenmelodie, Wartemelodie bei Weiterleitung/Parallelcall etc, vgl. https://en.wikipedia.org/wiki/Ringback_tone

**Comment by findingmarbles** [comment]
Dieses Feature hat sehr geringe Priorität und bauen wir voraussichtlich nicht. Trotzdem Danke für den Vorschlag!
