### ISSUE TITLE
Also available for sipgate ?

### ISSUE THREAD

**Issue by hanneshal** [sipgate/sipgate.io#26]
Hey there,

just saw your project and I like what you have done. Is it planned to enable this feature for sipgate clients (land-line)?
I'm looking for this feature since the REST API was released. I could retire all the REST "pull" requests ;)

regards

Johannes

**Comment by danielberlin** [comment]
More confusion on this issue, but availability for 'basic' seems to be not the case despite the fact that it is now mentioned here:

https://github.com/sipgate/sipgate.io/commit/ae74a8310d965a1d28d49e84b25ab414861b6b2b

**Comment by superbilk** [comment]
To clear this up: We are preparing a website relaunch of sipgate basic (working title was "go") that supports sipgate.io
You can already sign up and use sipgate.io with a "new" account, created at www.sipgate.de/go
Existing sipgate basic users will have this feature available soon.

**Comment by askeron** [comment]
Maybe you want to metion this in the readme.md or some where on the demo site because I waste quit some time with the try to book this feature with my (old) account. ;)

**Comment by andreasmo** [comment]
What about sipgate team? This would enable great integration-possibilities. Please don't forget your  paying customers..

**Comment by BlackMac** [comment]
We will clear up the situation regarding sipgate basic soon. sipgate team integration (beta) will also be available in just a few weeks.

**Comment by hanneshal** [comment]
Beta is now available for "Team" https://twitter.com/sipgateio/status/596263339791114240

**Comment by BlackMac** [comment]
We expect to enable sipgate.io in sipgate team for all signups through this form this week: http://goo.gl/forms/h2nSMbnFrk
