### ISSUE TITLE
Bug: If server at given sipgate.io URL down, calling impossible (reopening #31)

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#32]
Reopening #31.

Wenn kundenseitig der sipgate.io-Server down ist oder ich folgendes hinzufüge, sind weder ausgehende (Notruf!) noch eingehende Anrufe möglich. Verhalten dann wie in #31 beschrieben:

`iptables -I INPUT 1 -s push-api.sipgate.net -j DROP`

Auffällig dabei ist, dass Simquadrat einwandfrei funktioniert, wenn ich nur den Webserver abschalte. Ist er jedoch down(*) oder verwirft per o.g. iptables-Regel jegliche Pakete, tritt der Zustand der nicht mehr möglichen Anrufe ein.

Fazit: Entweder ist das derzeitige sipgate-seitige Timeout zu lang oder es greift nur bei entsprechenden ICMP-Antworten.

(*) Genau genommen eingefroren in einer Kernelpanik. In diesem Zustand sind etliche Linuxe sogar noch anpingbar (daher geben sie wahrscheinlich sogar noch ICMP-Rückmeldungen wie "port unreachable"), folglich ist dieser Zustand verschieden vom schlichten "server down", wo ein unmittelbares "host unreachable" vom Router kommt.

**Comment by fuglu** [comment]
Notrufe werden immer direkt zugestellt. Das haben wir jetzt auch in die Doku aufgenommen (a046fb0f64c36b931bda478ef8dc44108750723e).


> iptables -I INPUT 1 -s push-api.sipgate.net -j DROP

Das Timeout (zehn Sekunden) greift auch, wenn die Firewall zu ist. Grade extra nochmal mit deiner Regel getestet.

Das Timeout ist zur Zeit mit [RequestConfig.Builder](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/RequestConfig.Builder.html) realisiert.
Alternativ könnte man den POST Request in einen eigenen Thread auslagern und den Thread nach X Sekunden töten. Das würde allerdings auch Verbindungen töten, die einfach nur langsam sind. :confused: 


Sollten wir das Timeout evtl. einfach auf zB. fünf Sekunden runtersetzen???

**Comment by danielberlin** [comment]
1. Das Timeout sollte auf jeden Fall auf 5 s herabgesetzt werden. Zu überlegen wäre, ob man es nur für ausgehende auf 5 s und für ankommende weiterhin auf 10 s lässt, aber es spricht eigentlich nichts gegen 5 s für beides. (Ihr könnt ja nach einer Woche die Anzahl der durch das Timeout abgebrochenen Prozesse zählen, sollte ja nicht mehr als ein paar Prozent sein.)

2. Zum funktionalen Verhalten bei nichterreichbarem Server muss ich leider widersprechen, denn was ich mit o.g. iptables-Regel bekomme, ist die Ansage "Der Teilnehmer ist nicht erreichbar"; sipgate.io-Log sieht dann so aus:

```
28.01.2015 19:34:10	https://***.php	500 - Internal Server Error
Request:
from=49***&to=498003301000&direction=out
Response:
The target server failed to respond
```

Das passiert sowohl bei Anrufen zu SQ-Nummern als auch (wie hier gerade getestet) zur 08003301000.

**Comment by fuglu** [comment]
Bingo!

Du machst https und wir haben zum Testen http benutzt.
SSL ist allerdings das Problem:
https://issues.apache.org/jira/browse/HTTPCLIENT-1478

Wir schauen uns das morgen nochmal an und fixen das.

Vielen Dank für's Reporten! :+1: :clap:

**Comment by danielberlin** [comment]
Ich hoffe mal, dass es mit 4.3.6 gelöst ist. :-)

Play-URLs werden ja von `Apache-HttpClient/4.3.1 (java 1.5)` abgerufen, während bei der XML-Kommunikation `sipgate.io` als User-Agent übermittelt wird. Ist das so beabsichtigt? Zumindest wirft es die Frage auf, ob das nicht auch problematisch ist.
Z.B. funktioniert es bei mir nicht, wenn ich per `<Play><Url>` eine http**s**-URL übergebe. Lässt sich hier https-Unterstützung umsetzen? Und dann könnte man auch gleich einheitlich `sipgate.io` verwenden.

**Comment by TheCK** [comment]
4.3.6 hat leider nicht direkt out-of-the-box geholfen. Wir mussten noch ein bisschen was anpassen.

Jetzt sollte aber das Problem mit den hängenden Conntections bei kaputtem SSL-Handshake behoben sein. Der Timeout ist jetzt auch auf 5 Sekunden runtergesetzt.

@danielberlin Kannst du das nochmal mit deinem Szenario testen?

**Comment by danielberlin** [comment]
Funktioniert jetzt einwandfrei. Danke. :-)

Was ist mit den https-URLs für Play? Wird das auch bald unterstützt werden? Oder gibt es da Schwierigkeiten?
