### ISSUE TITLE
HTTPS in <Play><Url>

### ISSUE THREAD

**Issue by TheCK** [sipgate/sipgate.io#33]
@danielberlin #32 

Play-URLs werden ja von Apache-HttpClient/4.3.1 (java 1.5) abgerufen, während bei der XML-Kommunikation sipgate.io als User-Agent übermittelt wird. Ist das so beabsichtigt? Zumindest wirft es die Frage auf, ob das nicht auch problematisch (da verschiedene Instanzen/Versionen) ist.
Z.B. funktioniert es bei mir nicht, wenn ich per <Play><Url> eine https-URL übergebe. Lässt sich hier https-Unterstützung umsetzen? Und dann könnte man auch gleich einheitlich sipgate.io verwenden.

**Comment by TheCK** [comment]
Das ist intern schon das gleiche Stück Code. Ich gucke mir morgen mal an, ob ich es reproduzieren kann.

**Comment by TheCK** [comment]
@danielberlin 

Ich habe das grade nachgestellt und es hat funktioniert.

Was passiert denn wenn du das machst, wird der Befehl ignoriert, oder gibt es einen XML-Fehler im Log? Am Besten wäre es, wenn du uns ein Beispiel zukommen lassen könntest, mit Datum und Uhrzeit.

**Comment by danielberlin** [comment]
Es funktioniert jetzt einwandfrei, lediglich wenn die http*s*-URL auf einem SNI-VirtualHost liegt, gibt es Probleme. (Früher ging es auch auf einem SSL-VirtualHost ohne SNI (dedizierte IP) nicht.) Das ist aber eher Sache des Apache-HttpClient.
Kann geschlossen werden.
