### ISSUE TITLE
Anrufdauer

### ISSUE THREAD

**Issue by chrisribal** [sipgate/sipgate.io#34]
Schön wäre die Möglichkeit, Anfang als auch Ende eines Gespräches zu bekommen. So könnte man Statistiken über die Anrufdauer mit verschiedenen Nummern analysieren.

**Comment by findingmarbles** [comment]
Hi Chris! 
Seit letzter Woche kann man eine URL setzen, die beim Gesprächsende aufgerufen wird. Such einfach auf https://github.com/sipgate/sipgate.io nach "onHangup".

Cheerio, Corinna
