### ISSUE TITLE
Record, SMS2Mail & SMS event (was: Feature Requests)

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#36]
Es hat sich ja schon länger nichts mehr getan im Feature Store, daher folgende Anregungen:

* Empfang von Audiodaten (Ton-Mitschnitt)
 * Diese könnten unter einer URL bereitgestellt werden, die per sipgate.io XML Response zurückgegeben wird
 * Oder auf eine zu definierende URL gepusht werden. Diese URL wäre idealerweise direkt im XML anzugeben, z.B.
```
<Response>
    <Play>
        <Url>http://example.com/example.wav</Url>
    </Play>
    <Record push="toUrl">
        <Url>http://example.com/sipgateio/audiopush</Url>
    </Record>
</Response>
```

* SMS-To-Mail:

 * Übermitteln der empfangenen SMS per sipgate.io, falls überlange SMS (über 160 Zeichen) diese (ggf. im weiteren Schritt) zusammenfassen:
```
<SMS>
    <Content>
    Text
    </Content>
</SMS>
```

 * Kann auch direkt im XML angegeben werden für größtmögliche Flexibilität auf Kundenseite und für einheitliche, intuitive Verwendung innerhalb der sipgate.io API, z.B.
```
<Response>
    <IfSms>
        <Mail encryptTo="gpgfingerprint">sms2mail@example.com</Mail>
    </IfSms>
</Response>
```

**Comment by danielberlin** [comment]
Statt ''<IfSms>'' würde sich mittlerweile natürlich der hinzugekommene POST-Parameter "event=sms" anbieten.

**Comment by findingmarbles** [comment]
Alles was mit SMS zu tun hat, ist vertraglich schwierig. 
Tonmitschnitt ist ein spannendes Thema, aber erstmal nicht geplant. 

LG, Co
