### ISSUE TITLE
Feature Request: Fallback URL und Fallback Verhalten

### ISSUE THREAD

**Issue by askeron** [sipgate/sipgate.io#37]
Ich fände es super, wenn man einen Fallback angeben könnte, was sipgate.io machen soll, wenn die für sipgate.io hinterlegte URL nicht erreichbar ist, einen Timeout liefert oder einen andere HTTP-Statuscode als 200 zurückgibt.

Der Hintergedanke ist, dass ja kein Server 100% uptime hat bzw. könnte ja auch einfach einmal eine andere Komponente (z.B. die Datenbank) kaputt sein, so dass der Webserver einfach einen 500er Status zurückliefert.

Deshalb wäre es super, wenn es möglich wäre, eine Fallback-Response bei spigate zu unterlegen, die in einem solchen Fall angezogen wird. Zusätzlich wäre es natürlich noch besser, wenn man eine Fallback-URL angeben könnte, an die der Request im Fehlerfall geschickt würde. Hier könnte man dann ein redundantes System adressieren.

**Comment by CookieCrumb23** [comment]
Wir haben darüber diskutiert und sind zu der Meinung, dass das momentane Verhalten - d.h. der Anruf wird durchgestellt und die Account Einstellungen greifen - für die meisten Anwendungen momentan ausreichend ist.
