### ISSUE TITLE
Feature Request: Individuelle Spam-Behandlung

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#38]
Für den tellows Spamschutz wäre eine Behandlung in sipgate.io praktisch, man müsste entweder beim Push den Status als Spam (z.B. als weiteren Parameter nach in/out) übermitteln oder man schickt pauschal eine konditionale Antwort, was mit Spam passieren soll:

```
<Response>
   <If spam=true>
      <Play>
         <Url>https://example.com/spamansage.wav</Url>
      </Play>
   <If>
</Response>
```

**Comment by BlackMac** [comment]
Super Idee. Wir schauen uns mal an inwieweit wir Features in sipgate.io integrieren können. Danke.

**Comment by danielberlin** [comment]
Ich stelle mir hier im Prinzip eine Schnittstelle wie bei den Scores von SpamAssassin vor, d.h. sipgate.io schickt den tellows-Score mit, wodurch die individuelle Anrufbehandlung ermöglicht wird:

* mittlerer Score (cold calls, outbound call center): `<Response><Play><Url>https://example.com/keinezeitfuerumfragen.wav</Url></Play><Dial><Voicemail/></Dial></Response>`
* hoher Score (unseriös): `<Response><Play><Url>https://example.com/spitansage.wav</Url></Play><Hangup/></Response>`

* Darüber hinaus ergibt sich hier auch in Verbindung mit #22 die neue Idee, generell individueller mit der Weiterleitung umzugehen, z.B. je nach Score unterschiedlich viele Freizeichentöne abzuwarten, z.B.  Übergabe an Voicemail nach 4 Freizeichen `<Response><Dial waitRingTones="8"><Voicemail/></Dial></Response>`. So könnte man seriöse Anrufer erst nach vielen Freizeichen auf die Voicemail schicken und unseriöse schneller, damit man z.B. in Meetings von unwichtigen Anrufen nicht durch langes Klingeln gestört wird.

Weitere Ideen ergeben sich sicher auch aus RF5039: https://en.wikipedia.org/wiki/VoIP_spam#SPIT_Mitigation

**Comment by findingmarbles** [comment]
Dieses Feature bauen wir erstmal nicht. Wer das dringend braucht, kann das - dank offener Tellows API - selber bauen.
