### ISSUE TITLE
Setzen der ausgehenden Nummer

### ISSUE THREAD

**Issue by martini** [sipgate/sipgate.io#39]
Wenn ich Issue https://github.com/sipgate/sipgate.io/issues/24 richtig verstanden habe, kann man bei einem ausgehenden Anruf die caller-id setzen (keiner Weiterleitung, initiator des Anrufs nach aussen bin ich)?

Wenn das so ist, bei mir funktioniert es nicht (sipgate team).

Das XML sieht wie folgend aus:

&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;Response onHangup="https://xxx.znuny.com/api/v1/sipgate/hangup"&gt;
  &lt;Dial callerId="41715xxxxxx"&gt;
    &lt;Number&gt;&lt;/Number&gt;
  &lt;/Dial&gt;
&lt;/Response&gt;

Was mache ich falsch?

PS: Im "sipgate.io Log" werden mir generell keine Requests angezeigt (ist wohl nocht ein Bug).

**Comment by TheCK** [comment]
Das Log sollte jetzt funktionieren.

Um die CallerId bei ausgehenden Gesprächen zu verändern. muss in <Number/> die Nummer stehen, die ausgehend gewählt werden soll. Also in dem meisten Fällen die Gleiche die im POST request steht.

Siehe Beispiel 4 für das Dial-Command:

**Example 4: Set custom caller id for outgoing call**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
	<Dial callerId="492111234567">
		<!-- Originally dialed number, extracted from POST request -->
		<Number>4915799912345</Number>
	</Dial>
</Response>
```

**Comment by martini** [comment]
Wow! Vielen Dank für die schnelle Antwort!

1) Setzen der callerId hat leider noch nicht funktioniert. Ich beschreibe nochmal was ich eigentlich machen will:

Wenn ich einen outbound call starte will ich die callerId meines Anrufes je nach meinen Anruf-Ziel setzen. Dazu dachte ich, dass ich im Admin-Interface eine "URL für ausgehende Telefonate" setze und mit folgender Antwort die outbound callerId setzen kann:

```
<Response onHangup="https://xxx.znuny.com/api/v1/sipgate/hangup">
  <Dial callerId="417158xxxxx">
    <Number>4917141xxxxx</Number>
  </Dial>
</Response>
```

Leider ändert er die callerId nicht sondern startet weitere outbound calls (zumindest bekomme ich gleich weitere POST calls auf der "URL für ausgehende Telefonate").

 -> Ist mein UseCase überhaupt abzudecken?


2) Log
Danke, das ist nun vorhanden. Es steht dass ich hier die Calls "Requests aufklappen" könnte. Das geht leider nicht (in Safari und Chrome getestet).

**Comment by TheCK** [comment]
Eigentlich sollte der Use-Case genau so funktionieren.

Wir werden uns das anschauen, und auch die Log-Funktion noch einmal prüfen.

**Comment by martini** [comment]
Also, wenn das funktioniert! Dann wäre das eine 🚀

**Comment by TheCK** [comment]
Das Log sollte jetzt auch im Chrome und Safari funktionieren.

**Comment by martini** [comment]
Log funktioniert nun! Ein Traum! :)

**Comment by fnordian** [comment]
Bitte noch einmal testen. Das Setzen der CallerId sollte jetzt funktionieren.

**Comment by martini** [comment]
Funktioniert jetzt ausgezeichnet! Danke!

Eine Frage hätte ich noch, wie schnell muss meine http-Schnittstelle antworten? Ich hab zum test einen Sleep von 30 Sek. eingebaut, danach sieht es so aus also ob die Anfrage auf "URL für eingehende Telefonate" ignoriert wird.

**Comment by fnordian** [comment]
Die Antwort muss innerhalb von 5 Sekunden erfolgen, ansonsten wird sie ignoriert.

**Comment by martini** [comment]
Top! Danke!
