### ISSUE TITLE
Bug: ausgehender Anruf zusätzlich eingehend gepusht

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#41]
Details siehe simquadrat.zendesk.com #42406

Ausgehende Anrufe von sipgate.io werden nochmals als eingehend gepusht. Soweit ich es nachvollziehen konnte, tritt dieses Problem immer dann auf, wenn ich für den ausgehenden Anruf '<Dial callerId=...' als Antwort gebe.

Dieser Bug ist dahingehend gravierend, als dass ich direction=in zu unbekannten to-Nummern ablehne/auf die Voicemail schicke. Somit sind derzeit ausgehende Anrufe nicht mehr möglich!

Vermutlich tritt dies auf, seit die Parameter 'event' und 'callId' mit übermittelt werden, was vor wenigen Tagen eingeführt wurde.

**Comment by fnordian** [comment]
Bitte noch einmal testen.

**Comment by danielberlin** [comment]
Tritt nun nicht mehr auf.
