### ISSUE TITLE
Hangup unterscheidet nicht nach angenommen / nicht angenommen

### ISSUE THREAD

**Issue by pebosi** [sipgate/sipgate.io#42]
Bei dem Hangup Event gibt es keinen Unterschied ob der Anruf angenommen wurde oder nicht oder hab ich was übersehen?

**Comment by TheCK** [comment]
Das ist nur die erste Version für das Hangup. Da kommen in Zukunft noch weitere Informationen dazu.

**Comment by TheCK** [comment]
@pebosi Die Hangup-POST-Request senden jetzt den Grund für das Ende des Gespräches mit.

**Comment by pebosi** [comment]
Perfekt danke.
