### ISSUE TITLE
Beim Abspielen einer Sounddatei wird kein Hangup Befehl ausgeführt

### ISSUE THREAD

**Issue by BastianS1986** [sipgate/sipgate.io#43]
Wenn bei einem newCall Event eine Sounddatei abgespielt wird und gleichzeitig eine hangup URL übermittelt wird, wird diese ignoriert und nicht ausgeführt, wenn während dem Abspielen der Sounddatei aufgelegt wird.

Ich weiß nicht, ob das Absicht ist, oder noch nicht korrekt funktioniert

**Comment by BastianS1986** [comment]
Auch fällt mir auf, wenn ein Anrufer auf die Mailbox weitergeleitet wird, kein hangup ausgeführt wird

**Comment by danielberlin** [comment]
Was meinst Du mit Hangup bei Mailbox? Kann man 10 Minuten auf die Mailbox quatschen? Normalerweise kann man doch so viel aussprechen, bis die eine bestimmte Länge erreicht ist, z.B. 120 s, woraufhin die Mailbox dann auflegt, nicht aber sipgate.io. Oder hast Du eine Mailbox mit reiner Ansage?

**Comment by BastianS1986** [comment]
Beispiel: Jemand ruft bei mir an. Dann wird der newCall Event angestoßen.
Der Anrufer spricht nun drauf und legt irgendwann auf.
Daraufhin wird kein hangup Event angestoßen.

In meinem Fall signalisiert mir mein Script weiterhin ich sei am telefonieren und ich muss manuell wieder den Status zurücksetzen.

Beim Auflegen in der Mailbox sollte das Event meiner Meinung nach ebenfalls durchgeführt werden.

**Comment by danielberlin** [comment]
Vermutlich ist ``<Voicemail>`` nur eine interne Weiterleitung und daher weiß die sipgate.io-Schnittstelle dann nicht mehr, was mit der Voicemail-Instanz im weiteren Verlauf passiert, da der Anruf an den Voicemail-Server übergeben wurde? Dann dürfte das auch bei ``<Dial>`` nicht funktionieren.

**Comment by TheCK** [comment]
Wir schauen uns das an.

**Comment by TheCK** [comment]
@BastianS1986 Hangups sollten jetzt auch gepusht werden, wenn man während einer Ansage auflegt. Bitte nochmal testen.

**Comment by BastianS1986** [comment]
@TheCK Sieht gut aus, danke :)
