### ISSUE TITLE
Rufnummer unterdrücken nicht möglich

### ISSUE THREAD

**Issue by BastianS1986** [sipgate/sipgate.io#44]
Ich habe das Problem, dass trotz &lt;Dial anonymous="true"&gt; immer die im Dashboard hinterlegte freie Rufnummer mitgeschickt wird.

**Comment by TheCK** [comment]
Wir schauen uns das an.

**Comment by TheCK** [comment]
@BastianS1986 Ich habe das gerade getestet und bei mir hat es so funktioniert wie es soll. 

* Hast du es mit eingehenden oder ausgehenden Anrufen getestet?
* Ist die Nummer die angezeigt wird wirklich die freie Absendernummer oder vielleicht eine die du wirklich in deinem sipgate/simquadrat-Account hast?
* Und wenn es ein ausgehender Anruf ist: Bei welchem Anbieter liegt die Nummer, die du zum Testen anrufst?

Es wäre super wenn die diese Fragen beantworten könntest, dammit wir das Problem eingrenzen können.

**Comment by BastianS1986** [comment]
@TheCK 
- Es handelt sich hier um ausgehende Anrufe.

- Die Nummer, die auf dem Display bei mir am Telefon angezeigt wird, ist die freie Absendernummer.   Diese ist nicht bei Sipgate registriert.

- Telefonanbieter ist KabelBW bzw. Unitymedia

Wenn du fragst, ob es sich um eingehende oder ausgehende Anrufe handelt;
Kann ich bei eingehenden Anrufen ebenfalls das, was ich auf meinem Handydisplay sehe, modifizieren?
Das wäre ja genial und würde ich mir sofort auch noch mit einbauen ;)

**Comment by TheCK** [comment]
Jetzt kann ich es auch nachstellen.

Und ja, du kannst auch für eingehende Anrufe die Absendernummer beeinflussen.

**Comment by BastianS1986** [comment]
Was muss ich dann im XML bei Number eintragen?
Einfach leer lassen oder die angerufene Nummer von mir hinterlegen?

**Comment by TheCK** [comment]
in ```<Number>``` wie auch auch bei ausgehenden Calls immer die "to"-Nummer aus dem PUSH eintragen, wenn es an die selbe Nummer gehen soll. Leer lassen geht leider nicht.

**Comment by TheCK** [comment]
@BastianS1986 Rufnummernunterdrückung sollte wieder wie gewohnt funtionieren. Bitte nochmal testen. :)

**Comment by BastianS1986** [comment]
@TheCK Funktioniert perfekt, vielen Dank! :)

**Comment by danielberlin** [comment]
für eingehende Anrufe Absendernummer beeinflussen funktioniert bei mir nicht.

493099 exemplarisch meine SQ-Nr. und 491234567 die Nr., die für diesen eingehenden Anruf bei mir angezeigt werden soll:

``<Response><Dial callerId="491234567"><Number>493099</Number></Dial></Response>``

**Comment by TheCK** [comment]
@danielberlin sorry für die lange antworzeit. was passiert denn (oder passiert nicht), wenn du das machst? Wird die callerId des Anrufers angezeigt?

**Comment by danielberlin** [comment]
Ja, es wird alles unverändert prozessiert, als ich ``<Response></Response>`` gesendet hätte, d.h. die Originalrufnummer des Anrufers wird signalisiert.

**Comment by fnordian** [comment]
Sorry, es hat etwas gedauert. Kannst Du bitte nochmal testen?

**Comment by danielberlin** [comment]
Ja, bei eingehende Anrufen lässt sich jetzt die fromNumber verändern und wird so überall statt der originalen Absendernummer angezeigt.
