### ISSUE TITLE
onHangup funktioniert nur unzuverlässig

### ISSUE THREAD

**Issue by apoxa** [sipgate/sipgate.io#45]
Ich bastele gerade mit eurem meteorjs-Modul rum und das onHangup (siehe #34) funktioniert nur in etwa 40% der Fälle. Entweder ist das ein Bug in dem Modul oder eure API ruft es nicht richtig auf. So lässt sich zumindest eine Anrufdauer nicht immer nachvollziehen.

**Comment by BlackMac** [comment]
Verwendest du proxylocal? Das ist in letzter Zeit sehr unzuverlässig. Ich bin zu ngrok gewechselt.

**Comment by apoxa** [comment]
Ich hab das ganze auf Heroku mit dem meteorjs-buildpack laufen.

**Comment by danielberlin** [comment]
Taucht ein Hangup-Event, so es denn stattgefunden hat, denn überhaupt im .io-Log (Dashboard) auf? Ich sehe keine Hangups, obwohl die Hangup-Pushs in meinem Apache-Log auftauchen...

**Comment by apoxa** [comment]
Nein, Hangups tauchen nur im Log des Webservers auf. Im Dashboard sieht man die leider nicht.

**Comment by TheCK** [comment]
@apoxa passiert das nicht pushen nur bei bestimmten Fällen (z.B. wenn man auflegt nachdem man schon mit dem anderen Teilnehmer gesprochen hat kommt immer ein PUSH vs. wenn man während einer sipgate.io-Ansage auflegt kommt nie ein PUSH) oder kommt es selbst innherhalb eines Falles dazu, dass der Hangup nicht gepusht wird?

**Comment by TheCK** [comment]
@apoxa hangup sollte jetzt zuverlässig gepusht werden bitte nochmal testen.

**Comment by findingmarbles** [comment]
@apoxa Hangups erscheinen jetzt übrigens auch im Dashboard-Log. Haben wir direkt mal mitgemacht :)

**Comment by danielberlin** [comment]
Hangups im Dashboard war schon wichtig zum Debugger, Danke!

**Comment by apoxa** [comment]
@TheCK @findingmarbles Danke für den Hinweis. Ich werd's die nächsten Tage beobachten. Solange mach ich mal zu.
