### ISSUE TITLE
Outgoing Call Issue

### ISSUE THREAD

**Issue by adwait123** [sipgate/sipgate.io#46]
We are using the Sipgate team account. For a particular user we get the following response for outgoing calls.

from=&to=0049XXXXXXXX&direction=out&event=newCall&callId=5XXXXXXXX

As you can see the from parameter is blank. It is important to have both the numbers for generating reports. Please can you let me know if we are missing something in the settings part.

**Comment by CookieCrumb23** [comment]
Do you dial the number "by hand" on your phone or do you start the call via click2dial when this occurs?

**Comment by adwait123** [comment]
Some firefox extension. But it works for all the others expect this user.

**Comment by fnordian** [comment]
Could you please retry. Sorry, it took a while to reproduce the issue.
