### ISSUE TITLE
How can I get my error responses logged?

### ISSUE THREAD

**Issue by bascan** [sipgate/sipgate.io#47]
Hi,
We're integrating with the sipgate API and we're having a hard time troubleshooting issues with our customers, because our error responses are not being logged.

###### Here's an example:
A customer did not configure his account correctly on our side. When sipgate called our API on behalf of that customer, we responded with a 400 (bad request) and a detailed error message in the body. 

However, the customer didn't see that error message in the sipgate log, it only logged "null":

![sipgate-log](https://cloud.githubusercontent.com/assets/7222814/8134518/26eb0b2e-1130-11e5-87f5-597c6109b307.jpg)

Could you please fix this issue or tell us in which format we should send our error message back.

###### Note:
We tried a couple of ``<Response>...</Response>`` XML variations, but they didn't get logged as soon as the response status != 200.

**Comment by fuglu** [comment]
Setting a different ```Content-Type``` header could do the trick. ```text/plain``` or ```text/html ```.

**Comment by TheCK** [comment]
We do not parse the response body at all if the response in not a 200 OK.

**Comment by bascan** [comment]
It would be very helpful when you at least log the body of responses where status is not 200. That would make troubleshooting a lot easier for our clients. We return descriptive error messages, but they only see "null" in their log.

**Comment by fnordian** [comment]
We added bodies of non 200 responses to the log. Could you please confirm, that it is what you wanted.

**Comment by bascan** [comment]
Verified, thanks.
