### ISSUE TITLE
Probleme bei SSL mit SNI-Hosts

### ISSUE THREAD

**Issue by apoxa** [sipgate/sipgate.io#48]
Ich probiere gerade mit einem Uberspace und eigener Domain rum. SSL-Cert kommt von StartCom und ist eingetragen worden.
Im Browser sieht das erstmal gut aus, aber sipgate.io gibt mir jetzt jedesmal ein 500 zurück, mit folgender Meldung:

    hostname in certificate didn't match: <meinVHost> != <*.apoxa.echter.host> OR <*.echter.host> OR <echter.host>

Von deren Support habe die Info, dass es wohl an SNI liegt, was sagt ihr dazu?

**Comment by wiesson** [comment]
Danke für die Info, wir schauen uns das Problem gerade genauer an. 

Als Workaround sollte die Uberspace eigene Domain für deinen Space aber funktionieren: 

```bash
https://apoxa.deinuberspacehost.uberspace.de/sipgateio/
```
.htaccess
```
RewriteEngine On
RewriteRule ^sipgateio/(.*) http://localhost:deinport/$1 [P]
```

**Comment by apoxa** [comment]
Danke für die Info.

Der Workaround geht bei mir aber leider nicht, da die Anwendung direkt an deren Pound hängt (Meteor braucht ja WebSockets).

**Comment by danielberlin** [comment]
Eigentlich sollte HTTPClient SNI schon lange unterstützen:

https://issues.apache.org/jira/browse/HTTPCLIENT-1119

Verwendet sipgate.io keinen Standard-HTTPClient? Es geht jedenfalls nicht mit SNI, sipgate.io Error 500:

``hostname in certificate didn't match: <mysniname.de> != <webserversmainipsslcert.de> OR <webserversmainipsslcert.de>``

**Comment by TheCK** [comment]
Wir sind dran. Aber es wird leider noch etwas länger dauern.

**Comment by fnordian** [comment]
Es hat etwas gedauert, aber wir haben jetzt einen neuen HttpClient. Nochmal testen bitte.

**Comment by danielberlin** [comment]
Nach wie vor negativ. Wenn ich auf eine https-URL mit SNI umstelle, kommt: 

`sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by fnordian** [comment]
Unser Client sendet ssl.handshake.extensions_server_name in der Anfrage mit. Nach meinem bisherigen Verständnis ist das der Indikator für SNI. @danielberlin, dieser Fehler könnte von einem nicht akzeptablen Zertifikat stammen. Für selbst signierte Zertifikate muss die entsprechende Option in den sipgate.io Settings aktiviert sein.

**Comment by danielberlin** [comment]
Ich habe Zertifikate von StartSSL, die auf folgendem Livetest ein A Ranking bekommen:

https://www.ssllabs.com/ssltest/

Daher sollte es eigentlich schon klappen?!

"This site works only in browsers with SNI support." -- io Log meldet bei meinem über SNI (nicht-Default-Virtualhost) laufenden Zertifikat: `601 - HTTP_STATUS_601 SSL handshake failed`

Eines der Zertifikate läuft im Main-VirtualHost (d.h. ohne SNI) und nur damit funktioniert sipgate.io momentan.

**Comment by TheCK** [comment]
StartSSL ist für uns im Moment keine trusted CA, das heist du müsstest eigentlich den Public-Key bei uns hochladen (geht nur in simquadrat und basic) damit das Zertifikat überhaupt akzeptiert wird.

**Comment by danielberlin** [comment]
Security Request: Bitte StartSSL in den Certstore mit aufnehmen. :sweat_smile: 

https://www.startssl.com/certs/ca-sha2.pem

**Comment by fnordian** [comment]
Wir haben neue Zertifikate aufgenommen. Bitte nochmal testen.

**Comment by danielberlin** [comment]
SNI-Virtualhosts funktionieren jetzt einwandfrei. :sunglasses:

Kann geschlossen werden.

**Comment by BlackMac** [comment]
Danke.
