### ISSUE TITLE
Google Script und Redirects

### ISSUE THREAD

**Issue by StefanHaeck** [sipgate/sipgate.io#49]
Der Sipgate Post-Request folgt keinem 302 Redirect, was jedoch bei der Nutzung von sipgate.io in Verbindung mit dem Content Service von Google Scripts notwendig wäre. 

Hier der entsprechende Link zur Google Dokumentation:
https://developers.google.com/apps-script/guides/content#redirects

**Comment by DennisBecker** [comment]
Ich sehe das auch als wichtiges Feature für Anbieter. Man kann ja schlecht erwarten, dass die eigenen Kunden in kurzer Zeit die neue URL eintragen, wenn der Dienst geändert wird.

**Comment by wiesson** [comment]
@StefanHaeck 
Der POST-Request folgt nun korrekt dem Redirect. Bitte einmal testen und ggf. Feedback geben!

**Comment by StefanHaeck** [comment]
@wiesson 
Super funktioniert! Danke!
