### ISSUE TITLE
Individuelle Steuerung vorhandener Features wie Parallelruf und Tarifansage

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#50]
Feature Request:

* sipgate.io-Ansteuerung des Parallelrufs, um diesen nur für wichtige Anrufer fallweise zu nutzen, momentan kann man ja fallweise nur weiterleiten:

```xml
<Response>
  <ParallelDial><Number>4921123</Number></ParallelDial>
</Response>
```

* Parallelruf als Multi-Parallelruf, d.h. alle angegebenen `<Number>` werden parallel angewählt. Hier fallen mir mehrere Szenarien ein, z.B. fallweise bestimmte wichtige Anrufe zuhause, im Büro und auf dem Handy von Gattin/Sohn/Tochter parallel signalisieren ("Hauptsache, jemand geht ran, egal wer"):

```xml
 <Response>
  <ParallelDial>
    <Number>49170123455</Number>
    <Number>49171998877</Number>
    <Number>49176112233</Number>
  </ParallelDial>
</Response>
```

* Für Parallelruf und Weiterleitung wäre ein `<Delay>5</Delay>` praktisch, um erstmal eine bestimmte Anzahl Sekunden/Freizeichen abzuwarten.

* Tarifansage: Statt im Dashboard generell zu aktivieren, wäre das Setzen nur für bestimmte Ziele praktisch (bzw. generell aktivieren und für bestimmte Ziele, z.B. Community und 9 Ct. zu allen +49 Zielen per io deaktivieren), so dass man bei ausgehenden Anrufen `<Response><CallAnnounce/></Response>` sendet, z.B. nur für Auslandsziele – und alles, was 9 Ct. kostet, braucht nicht angesagt zu werden (auch für interne Telefonate bei team bzw. SQ community interessant, diese schneller ohne Ansage aufzubauen, da man den Preis ja kennt). Kann später noch um Schalter "bei kostenlosen Anrufen unterdrücken" im Dashboard und `<Response><CallAnnounce ifBillable/></Response>` erweitert werden.

* In Verbindung mit #23 dann bequem (oder derzeit bereits, wenn man sich so eine Ansage generiert und per `<Play>` angibt) ließen sich auch eigene Tarifansagen entwerfen, z.B. `<Say voice="female">Dieser firmeninterne Anruf ist kostenfrei</Say>`

**Comment by findingmarbles** [comment]
Danke für Deine diversen Vorschläge, danielberlin! Wir sind sie heute nochmal durchgegangen:

* Parallelruf an mehrere Leute: Werden wir voraussichtlich umsetzen
* Tarifansage: Werden wir nicht umsetzen

Da hier versch. Sachen vermixt sind, die wir unterschiedlich behandeln werden, schliessen wir erstmal die Issue. Wir haben Parallelruf trotzdem auf dem Plan.

**Comment by danielberlin** [comment]
Bin gespannt, Parallelruf wird dann mit die vielseitigsten Möglichkeiten bieten. :-)

Tarifansage – würde schon reichen, wenn man im Dashboard ein weiteres Häkchen "9 Ct. Standardanruf davon ausnehmen" (auch Community, sofern noch Freiminuten übrig) setzen könnte. Die Ansage brauche ich wirklich nur für die 1-2 % Anrufe, die z.B. ins Ausland gehen, bei inländischen Gesprächen ist schnellerer Rufaufbau wichtiger.
