### ISSUE TITLE
Bei eingehender Weiterleitung falsche Nummer in to-Parameter

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#51]
Bis ca. letzte Woche Donnerstag wurden auf einer der SQ-Rufnummern eingehende Weiterleitungen in sipgate.io GET-Parameter `to` stets korrekt angezeigt. Seitdem jedoch ist `to` immer die SQ-Nummer, auf die die Weiterleitung gesetzt wurde, und nicht mehr die ursprünglich vom Anrufer gewählte Rufnummer, was sehr umpraktikabel ist.

Beispiel:

1. Beispiel: Anruf auf 0173xxx, Umleitung bei Nichterreichbarkeit auf 01579 (SQ) eingestellt
  * `to` vorher: 0173xxx
  * `to` jetzt: 01579xxx

2. Beispiel: Anruf auf Sipgate basic Rufnummer 030xxx, Umleitung nach 10 Sekunden auf 030xyz (SQ) eingestellt
  * `to` vorher: 030xxx
  * `to` jetzt: 030xyz

Woher kommt der Wert des `to`-Parameters im Push-String? Die SQ-Nummer braucht eigentlich gar nicht übermittelt zu werden, da ich sie ja kenne, während die original vom Anrufer gewählte Rufnummer die interessantere ist. Oder es sollte alternativ zusätzlich toDialled übermittelt werden.

**Comment by TheCK** [comment]
Wir habens uns das jetzt nochmal angeschaut und ein wenig umgebaut. In `to` wird jetzt weiter die Nummer des Accounts angezeigt. Wir haben aber einen (zur Zeit experimentellen) zusätzlichen Parameter `diversion` eingeführt, in dem die ursprünglich angerufenene Nummer steht.

Ich hoffe unsere Lösung ist soweit ok.

**Comment by danielberlin** [comment]
OK, damit kann ich die Funktionalität wie gewünscht wiederherstellen.

Wobei wie gesagt die SQ-Nummer bekannt ist, d.h. `diversion` ist für mich der wichtigere Parameter und `to` relativ uninteressant. Wenn ich von einem externen Anschluss (z.B. Vodafone 0173zyx) eine Weiterleitung zu SQ lege und bei sipgate.io dann ein Anruf mit to=0173zyx eingeht, kann ich ihn (wie früher) einwandfrei behandeln und außerdem ist mir bereits vorher bekannt, dass ein Anruf über 0173zyx nur durch die von mir gesetzte Weiterleitung eingehen kann. Daher fand ich das Verhalten wie bis vorletzte Woche besser. (Je mehr Parameter, desto komplexer wird das Ganze, sowohl für den Kunden zu verstehen als auch hinsichtlich vermehrter Supportanfragen.)

**Comment by TheCK** [comment]
Wir teilen deine Bedenken durchaus. Für einen SQ-Account ist es vielleicht auch nicht unbedingt erforderlich, da Dieser noch recht überschaubar ist. In einem Team-Account gibt es allerdings recht viele Benutzer und wahrscheinlich will man schon wissen, auf welchem Benutzer der Anruf gerade eingeht.

**Comment by danielberlin** [comment]
Und wenn man das Ganze herumdreht, `to` wieder wie früher und `diversion` können dann die team-Kunden für ihre special cases verwenden? Zumindest habe ich mich gewundert, als plötzlich ein Anruf reinkam, der da gar nicht hätte hereinkommen können, bis ich gemerkt habe, dass `to` nicht mehr exakt das `to` war wie früher. Manche Kunden testen da sicher auch umfangreich, dann wäre es schon gut, wenn sich Parameter nicht plötzlich verändern. Oder aber man macht es im ChangeLog transparent.

**Comment by TheCK** [comment]
Wir haben entschieden, das mit dem `diversion` jetzt so zu lassen und das Ganze auch schon dokumentiert. Wir finden, dass das die logischere Variante ist, da `to` die angerufene sipgate-Nummer beinhalten sollte.

**Comment by danielberlin** [comment]
Wird es auch über Versionsnummern (minor release numbers) dokumentiert wie früher? :-) https://github.com/sipgate/sipgate.io/releases
(Wenn erstmal die kritische Masse an team-Kunden .io nutzen, könnt es sogar notwendig werden, neue Versionen, auch und besonders wenn nur ein Parameter geändert wird, nicht an alle Kunden auf einmal auszurollen.)
