### ISSUE TITLE
Setzen der ausgehenden Nummer II / sipgate team

### ISSUE THREAD

**Issue by martini** [sipgate/sipgate.io#53]
Ich habe festgestellt, dass das setzen der callerId nicht mehr funktioniert. Hatte es aber früher schon am laufen. Folgendes ist meine http-Response welche ich auch im sipgate.io Log sehen kann (200 ok).

&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;Response onHangup="https://test.znuny.com/api/v1/sipgate/hangup"&gt;
  &lt;Dial callerId="4930609854180"&gt;
    &lt;Number&gt;491714100301&lt;/Number&gt;
  &lt;/Dial&gt;
&lt;/Response&gt;

Leider wird beim Empfänger aber immer keine Telefonnummer angezeigt (Basiseinstellung aus secure.live.sipgate.de) angezeigt. Es sieht so aus, als ob das Setzen der callerId ignoriert wird (selbes Verhalten wir mein ursprünglicher Bug-Report https://github.com/sipgate/sipgate.io/issues/39 ).

Über Feedback würde ich mich freuen.

**Comment by TheCK** [comment]
Ich habe gerade versucht das Problem nachzustellen, allerdings klappt es bit mir ohne Probleme. Handelt es sich bei dem weitergeleiteten Call um einen ausgeheneden oder eingehenden Call?

**Comment by martini** [comment]
Es ist ein ausgehender Call. Hilft evtl. dieser Request-String aus dem sipgate.io Log etwas?

ausgehend	30.06.2015 07:32:52	https://portal.znuny.com/api/v1/sipgate/out	200 OK

from=1452406e0&to=491714100300&direction=out&event=newCall&callId=5930108064835725888

**Comment by martini** [comment]
Ich habe ein interessante Feststellung.

1) Das setzen der CallerId geht, sobald ich irgend eine Absenderrufnummer in secure.live.sipgate.de gesetzt habe.

2) Setze ich die Absenderrufnummer in secure.live.sipgate.de auf "Unterdrückt" (hatte ich bisher als Fallback gemacht, falls das setzen der CallerId aufgrund von Netzwerk o. ä. schief geht), dann kann ich die CallerId nicht mehr überschreiben. -> Das hat früher jedoch funktioniert.


=> Was soll ich nun tun?

**Comment by TheCK** [comment]
Genau das ist uns auch schon aufgefallen. Der Workaround ist im Moment so wie 1), bis wir das Problem behoben haben.

**Comment by fnordian** [comment]
Das Setzen der CallerId bei ausgehenden Calls per API funktioniert jetzt auch, wenn im Account "Unterdrückt" konfiguriert ist. Bitte nochmal testen.

**Comment by martini** [comment]
Danke. Funktioniert nun!
