### ISSUE TITLE
Feature Request: Ausgehenden Anruf initiieren per Script

### ISSUE THREAD

**Issue by lcars79** [sipgate/sipgate.io#54]
Ich habe ein NodeJS Script welches in einem Fehlerfall einen Anruf auslösen soll (es reicht nur eine Nummer anzuklingeln). Ich dachte ich könnte das mit sipgate.io realisieren doch kann man hier nur mit einen ausgehenden Anruf reagieren wenn ein Anruf schon gestartet oder ankommt. 
Es wäre ein tolles Feature wenn ich einen Anruf auch von meinem Skript aus starten könnte. Dazu müsste ich aber mit euren Server sprechen und nicht nur auf ein POST von euch reagieren. Wäre es vorstellbar das ihr dies umsetzen könntet oder seht ihr andere Möglichkeit einen Anruf von einem Script aus zu triggern?

**Comment by TheCK** [comment]
Das geht jetzt schon für alle sipgate Produkte außer simquadrat über die XML-RPC-API von sipgate:

Für sipgate Plus ist die Dokumentation dazu hier: http://www.sipgate.de/img/sipgate_api_documentation.pdf

Und für die restlichen sipgate Produkte hier: http://www.sipgate.de/static/sipgate.de/downloads/api/sipgate_API.pdf

**Comment by lcars79** [comment]
Danke für den Tipp. Das werde ich gleich mal ausprobieren :-)

**Comment by danielberlin** [comment]
Die API hatte ich gar nicht (mehr) auf dem Schirm. Das ist ja auch ein Alleinstellungsmerkmal von Sipgate, vielleicht auch gut im Feature Store und Blog bewerbbar?

Vorher bitte noch einmal BibTeX laufen lassen, in http://www.sipgate.de/static/sipgate.de/downloads/api/sipgate_API.pdf ist nämlich die Bibliography `[?]` noch nicht einkompiliert. :-)
