### ISSUE TITLE
Weiterleitung via io defekt (congestion)

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#55]
Für bestimmte, sehr wichtige eingehende Anrufe wäre ein per io steuerbarer Parallelruf ideal. Da dies momentan nicht möglich ist, behelfe ich mir hier mit einer Weiterleitung. Seit ich dies vor einigen Monaten zuletzt erfolgreich getestet habe, funktioniert diese Weiterleitung per io momentan nicht mehr:

* Auf SQ kommt ein Ruf von 49304000 auf der 4930123456 an und soll an 4930776688 weitergeleitet werden (besser wie gesagt Parallelruf):
```xml
Request: from=49304000&to=4930123456&direction=in&event=newCall&callId=46709
Response:
<?xml version="1.0" encoding="UTF-8"?>
<Response><Dial><Number>4930776688</Number></Dial></Response>
```
* Der Anschluss 4930776688 ist weder besetzt noch wird der Anruf signalisiert, jedoch wird in SQ auf 4930123456 bereits ein ausgehendes Gespräch mit 9 Ct. berechnet, das nicht zustande gekommen ist. Am Anschluss von 49304000 höre ich jedoch weder ein Freizeichen noch eine Voicemail noch irgendwas, was auf ein aufgebautes Gespräch hindeuten würde.

* Beim initiierenden Anschluss 49304000 wird im Hangup-Event `congestion` geloggt:

`Request: event=hangup&callId=8440375548925316618&cause=congestion`

* Beim empfangenden SQ-Anschluss `chanunavail`, wenn das Ziel ein sipgate-externer Anschluss ist:

`Request: event=hangup&callId=467098492173953073&cause=chanunavail`

* In allen Fällen klingelt der Zielanschluss nicht und es ist auch kein Freizeichen zu hören! Zum Testen habe ich den Anruf mit callerId 49304000 auf einem weiteren go Anschluss initiiert:

```xml
Request: from=4930998877&to=4930123456&direction=out&event=newCall&callId=84403
Response:
<?xml version="1.0" encoding="UTF-8"?>
<Response><Dial callerId="49304000"><Number>4930123456</Number></Dial></Response>
```

* Ich dachte zuerst an die Tarifansage als Ursache für ein nicht zustande gekommenes, aber berechnetes Gespräch, aber dann hätte ich ja sowohl auf der 49304000 ein Freizeichen oder sogar die Tarifansage hören und am Zielanschluss ein Klingeln wahrnehmen müssen, was nicht der Fall war.

Frage: Die Kosten sollten erst anfallen, wenn das weitergeleitete Gespräch zustande gekommen ist?

**Comment by TheCK** [comment]
Kannst du uns dazu mal echte Beispieldaten zukommen lassen. Mit Datum/Uhrzeit und den richtigen Nummern, am besten an karsten@sipgate.io.

**Comment by danielberlin** [comment]
Mail ist raus.

**Comment by TheCK** [comment]
Hast du meine Antwort bekommen?

Die Weiterleitung bei uns hat gegriffen, allerdings hat deine FritzBox den Call mit 603 abgelehnt.

**Comment by TheCK** [comment]
Das sollte jetzt funktionieren.

**Comment by danielberlin** [comment]
Leider nein, jetzt gibt es einen neuen Bug: Die ausgehend gesetzte callerId wird beim angerufenen Anschluss im Dashboard richtig angezeigt, im dortigen io-Log allerdings steht die originale Rufnummer, nicht die aus callerId. Mail mit Details ist unterwegs.

**Comment by danielberlin** [comment]
Funktioniert nach erneutem Test.
