### ISSUE TITLE
Ausgehend anonyme Anrufe: from-Parameter

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#56]
Wenn ich bei go im Dashboard die Rufnummernunterdrückung aktiviere, werden Anrufe mit leerem `from` gepusht:

`from=&to=4930998877&direction=out&event=newCall`

Bei SQ dagegen (`#31#` am Handy) ist es besser, da hier beim Anrufer die Nummer nicht angezeigt wird und ich `from` zur Auswertung zur Verfügung habe:

`from=49157912345&to=4930998877&direction=out&event=newCall`

Bei go sollte `from` nicht leer sein. Die tatsächliche Absenderrufnummer ist sicher praktisch, aber mir wäre hier wichtiger zu wissen, dass sie gerade unterdrückt wurde (also `from=anonymous` präferriert). (Ich bin tendenziell eher gegen Einführung eines zusätzlichen Parameters extra dafür, aber vielleicht gibt es einen guten Kompromiss.)

**Comment by TheCK** [comment]
Da sollte jetzt wieder wie gewohnt "anonymous" in dem Parameter stehen.

Bitte nochmal testen

**Comment by danielberlin** [comment]
Funktioniert.
