### ISSUE TITLE
Anruferliste im Dashboard nicht vollständig

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#57]
Gewisse Anrufe tauchen in der Anruferliste des Dashboards nicht auf, anscheinend hat es mit sipgate.io zu tun: Festgestellt habe ich dies bei:

* Ausgehende Anrufe von go zu anderen Nummern (Sipgate), wenn `<Dial callerId='49157912345'>` gesetzt ist.

* Die Weiterleitung von go->SQ taucht nicht auf, weder im Dashboard bei go noch bei SQ, anscheinend auch unabhängig von sipgate.io.

* Vor einigen Wochen wurden auch Anrufe von SQ zu SQ nicht angezeigt, das funktioniert inzwischen.

Über sipgate.io werden diese Anrufe korrekt gepusht. Es betrifft also nur das Dashboard, scheint aber nur dann aufzutreten, wenn sipgate.io aktiviert ist.

**Comment by fnordian** [comment]
Damit kann ich hier nicht viel anfangen. Prinzipiell funktioniert es. Schreib am Besten die genauen Daten der fehlerhaften Calls per Mail an marcus@sipgate.io. Dann kann ich mich besser darum kümmern.
