### ISSUE TITLE
Verhalten bei zu langsamer io-Antwort

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#58]
Ich habe mir gerade nochmal das Verhalten angeschaut, wenn mein io-Skript zu langsam antwortet. Bei eingebauter Verzögerung (die tritt sonst ab und an mal auf, wenn eine Zwischenprozedur länger dauert und wird schon bei >> 4 s kritisch, vgl. #32) passiert folgendes, hier die entscheidende letzte Zeile:

```php
ignore_user_abort(true);
$dom = new DOMDocument('1.0', 'UTF-8');
echo $dom->saveXML();
flush();
system("sleep 10");
```
1. Die XML-Response wird sofort ausgegeben, aber die TCP-Verbindung hält mein Webserver noch so lange offen, bis der Rest (`sleep`) abgearbeitet ist.

2. Im sipgate.io-Log erhalte ich daher `600 - General IO Error – timed out` (der Ruf wird dann einfach so aufgebaut, ohne Ansage, callerId o.ä.), da vorher der Timeout (siehe #32) greift.

3. `system("sleep 10 >/dev/null &")` – nicht aber `system("sleep 10 &")` – würde hier bereits den erwünschten Effekt erreichen.

* Am Besten wäre es natürlich, wenn sipgate.io nach Erhalt des schließenden Tags `...</Response>`bzw. `<Response/>` sofort loslegt und von mir aus gerne die TCP-Verbindung zu meinem Server direkt kappt. Damit das keine Probleme bereitet, habe ich am Anfang in meinem Skript `ignore_user_abort(true)`.

* Welche der drei folgenden Timeouts verwendet denn momentan io, vielleicht lässt es sich auch damit optimieren?
http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/RequestConfig.Builder.html#setConnectionRequestTimeout(int)

**Comment by danielberlin** [comment]
Tatsächlich verhält sich `sleep` anders als das, was momentan die eigentliche Ursache darstellt (DDoS bei Telegram; https://twitter.com/telegram/status/619515927353278464). Ich kann aber mit der Umleitung des Outputs auf `/dev/null` erreichen, dass ein `system`-Aufruf in den Hintergrund geforkt wird:

`$pid = system("timeout 90 telegram-cli -W -e 'msg $to $msg' -D >/dev/null &1 &");`

Dennoch wäre es nicht verkehrt, wenn io nach Erhalt des schließenden Tags direkt loslegen würde. :-)

**Comment by fnordian** [comment]
Zur Zeit können wir dieses Verhalten leider nicht unterstützen, da die Umsetzung zu Aufwändig ist. Wenn ein Server in der Lage ist, eine Antwort zu generieren, sollte er auch in der Lage sein, die HTTP-Verbindung zu schließen. Von daher sehen wir keinen echten Mehrwert. 

Der bisher gewählte Timeout von 5s ist ein von uns gewählter Kompromiss und wir hoffen, damit die meisten Anwendungsfälle abdecken zu können. Langläufige Prozesse sollte, wie beschrieben asynchron behandelt werden. Das Generieren der Antwort sollte ohne Verzögerung geschehen.
