### ISSUE TITLE
Sipgate Team: .io-Verhalten bei Gruppen/Benutzern

### ISSUE THREAD

**Issue by tobiashieb** [sipgate/sipgate.io#59]
Wir haben Sipgate Team so konfiguriert, dass bei einem eingehenden Anruf auf einer Gruppen-Rufnummer an die jeweiligen Benutzer weitergeleitet wird. Leider erhalten wir bei einem eingehenden Gruppenanruf keine "Incoming Call" Events auf Benutzerebene. 

Wir würden uns wünschen, dass .io genau das "Klingelverhalten" abbildet. Bedeutet: 

1. eingehender Anruf auf Gruppenrufnummer 
2. Weiterleitung an 3 Benutzer
3. Die 3 Telefone der Benutzer klingeln - sipgate.io signalisiert für jeden Benutzer einen eingehenden Anruf (from = Telefonnummer des Anrufers; to = Telefonnummer der angewählten Gruppe)
4. Nimmt ein Benutzer den Anruf entgegen, wird der Call bei dem entsprechenden Benutzer "active" - bei den anderen kommt das "cancel" Event an. 

Es ist zwar möglich, eine Gruppenrufnummer für sipgate.io zu aktivieren - allerdings kommt dann nur ein Event an (eingehender Anruf an Gruppenrufnummer) - das die Telefone nun bei X Benutzern klingeln, signalisiert sipgate.io leider nicht.

**Comment by mxzinteract** [comment]
Genau dieser use case wird auch von mehreren unserer Pilotkunden als kritisches Feature gewünscht.

**Comment by tobiashieb** [comment]
Umschiffen ließe sich das Problem über einen Parallelruf, den man via XML Response ausführt. Dafür gibt es ja bereits ein Issue (#50).

**Comment by merlink01** [comment]
+1

**Comment by findingmarbles** [comment]
Hi @tobiashieb, @mxzinteract, @merlink01 !

Inzwischen schreiben wir ja bei einem Gruppenanruf die Gruppenmitglieder mit ins newCall-Event:
https://github.com/sipgate/sipgate.io/blob/master/README.md#new-call

Deckt das eure Anwendungsfälle ab?

Cheers, Corinna

**Comment by merlink01** [comment]
Für mich ja.
