### ISSUE TITLE
Nummer des Anrufers in einer E-Mail zu einer Mailbox-Benachrichtigung via .io um Namen ergänzen

### ISSUE THREAD

**Issue by tosie** [sipgate/sipgate.io#60]
Hinterlässt jemand eine Nachricht in einer Mailbox, wird diese als MP3 in einer E-Mail an den Empfänger zugestellt. Die E-Mail enthält Meta-Daten wie z.B. die Nummer des Anrufers, die angerufene Name, Datum, Uhrzeit, ...

Die Nummer des Anrufers könnte via sipgate.io mit einem Namen ergänzt werden. Der Mailbox-Service "fragt" via sipgate.io nach einem Namen zu einer Nummer und übernimmt diese Information in die Benachrichtigungs-E-Mail.

**Comment by danielberlin** [comment]
Man könnte das auch (zusätzlich zum Vorschlag meines Vorredners) mit "Kontakte" verknüpfen. Einen gleichnamigen Menüpunkt habe ich in meinem Dashboard entdeckt, konnte aber noch nicht herausfinden, was funktional dahintersteckt. Außer "Importieren von Google" (da tut sich aber nix bei mir).

**Comment by findingmarbles** [comment]
@tosie Das kann man jetzt schon selber bauen, wenn man zusätzlich die XML RPC API (http://www.sipgate.de/static/sipgate.de/downloads/api/sipgate_API.pdf) bemüht.

Beide Vorschläge können wir uns langfristig vorstellen direkt in .io zu lösen. Ist jedoch so weit weg am Horizont, dass wir die Issue für jetzt erstmal schließen.

Trotzdem danke!

**Comment by tosie** [comment]
Schade, aber vielleicht wird es zukünftig ja was. Denn wenn ich es richtig verstehe, müsste ich mit der XML-RPC-API ein (weiteres) Adressbuch auf den sipgate-Servern synchron halten, was ich natürlich nicht möchte.

Ich teste es bei Gelegenheit trotzdem mal aus ...
