### ISSUE TITLE
Ereignis bei Anrufvermittlung

### ISSUE THREAD

**Issue by soaTf** [sipgate/sipgate.io#61]
Wir nutzen sipgate.io (erfolgreich) für die Darstellung des Anruferaufkommens in unserer Hotline (u.a. auch zur Zuordnung von Kundendaten etc.).
In diesem Kontext wäre es schön, wenn Weiterleitungen eines Anrufes ebenfalls, z.B. als neues "onRedirect"-Event, bereitgestellt werden können.
Hintergrundszenario:
- Ein Anruf geht auf einer Gruppen-Nummer ein (POST)
- Ein Mitglied der Gruppe nimmt den Anruf entgegen (Push onAnswer-URL)
- Der Anruf wird nun vom Mitarbeiter an eine andere Nebenstelle weitegeleitet -> diese Information kann aktuell m.e. nicht ermittelt werden

Oder gibt es hier ggf. andere Ansätze?

Vielen Dank

**Comment by maxnowack** [comment]
+1

**Comment by merlink01** [comment]
+1

**Comment by danielberlin** [comment]
+1

**Comment by leachiM2k** [comment]
+1

**Comment by Harald2** [comment]
+1

**Comment by findingmarbles** [comment]
Scheint uns das gleiche zu sein wie #75, daher die gleiche Antwort:

Haben wir auffem Schirm. Wollen wir langfristig machen, hat aber niedrige Prio. Daher schliessen wir das Ticket erstmal.
