### ISSUE TITLE
Minor bug: Umlautschwund in user[]

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#62]
Wenn ein Benutzer z.B. Jörg Mustermann heißt, übermittelt sipgate.io seinen Namen ohne Umlaute:

`&user%5B%5D=Jrg+Mustermann`

Bei team lässt sich der Name ändern und daher halb so schlimm, wenn man dann "ö" in "oe" ändert, jedoch bei Simquadrat nicht – oder doch?

**Comment by maxnowack** [comment]
Sollte statt dem Namen nicht besser eine eindeutige User-ID übergeben werden?

**Comment by findingmarbles** [comment]
Wir hatten über IDs nachgedacht und fanden Namen besser, weil sie die einfachere Zuordnung erlauben. Der Name ist das, was man im Account sieht. Eine ID zeigen wir nicht explizit.

**Comment by BlackMac** [comment]
Wäre es OK, wenn wir die Emailadressen der User als ID verwenden würden?

**Comment by danielberlin** [comment]
Am Besten Flexibelsten wäre es doch, wenn bei SQ der Name, den man sich oben im Reiter des Dashboard selbst setzen kann (Default: ${meinvorname}s Handy) und bei Team der sowieso selbst setzbare verwendet werden würde. Aber Umlaute sollten dann nachrangig auch funktionieren.

**Comment by tobiashieb** [comment]
E-Mail Adressen als Unique IDs wären imho besser. So könnten wir ein automatisches Matching mit unseren Usern realisieren. Mit der Übermittlung von Namen können wir nicht wirklich was anfangen…

**Comment by danielberlin** [comment]
Gutes Argument, habe nichts gegen E-Mail-Adressen.

**Comment by CookieCrumb23** [comment]
Wir würden gerne verstehen, warum Namen problematisch sind.
Warum erlauben die Namen kein gutes automatisches Matching?

(Das mit den Umlauten wird natürlich gefixt)

**Comment by tobiashieb** [comment]
Dazu fallen mir folgende Punkte ein:

1. Namen sind nicht eindeutig. Was passiert, wenn es zwei Leute im Team mit Peter Müller gibt?

2. Wie lang dürfen Namen sein? Limitiert Sipgate die Anzahl der Zeichen? Heftiges Beispiel: Ernst August Albert Paul Otto Rupprecht Oskar Berthold Friedrich-Ferdinand Christian-Ludwig Prinz von Hannover Herzog zu Braunschweig und Lüneburg Königlicher Prinz von Großbritannien und Irland

3. Was ist mit Sonderzeichen? Denke da an Namen wie "Chloé"

**Comment by merlink01** [comment]
Ideal wäre eine art dictionary mit der sipid und dem namen. 
Namen könnte man wie links encodieren oder einfach als base64. 
Alternatv könnte man statt der sipid auch die email nehmen, aber es ist ja möglich das mehrere anschlüsse unter einer email angelegt werden, somit ist die sipid ideal.
Wenn ein dictionary nicht übertragen werden kann empfehle ich das dict erst json und den string dann base64 zu encodieren.

**Comment by CookieCrumb23** [comment]
Das mit den Umlauten sollte jetzt funktionieren.
Für den Rest überlegen wir uns noch was.

**Comment by danielberlin** [comment]
Ich will nochmal meinen o.g. Vorschlag https://github.com/sipgate/sipgate.io/issues/62#issuecomment-130090250 aufgreifen, bei basic und Simquadrat `user` aus dem Dashboard zu beziehen, und zwar vom Reiter, da der dortige Name selbst wählbar ist. Dann hat das auch eine echte Funktion. :sunglasses:
