### ISSUE TITLE
Hangups werden manchmal nicht gesendet

### ISSUE THREAD

**Issue by merlink01** [sipgate/sipgate.io#64]
Hin und wieder kommt es vor, dass kein hangup ausgeführt wird.

Bei uns tritt das Problem momentan 1-2 mal täglich auf.

Oftmals bei Ausgehenden Anrufen.

**Comment by TheCK** [comment]
Wir haben da noch ein Problem behoben. Bitte nochmal testen.

**Comment by merlink01** [comment]
Sieht gut aus: Kein fehler in den letzten 500 einträgen.
