### ISSUE TITLE
Keine Information der Endpunkte mehr

### ISSUE THREAD

**Issue by merlink01** [sipgate/sipgate.io#65]
nach dem Umstieg von Team Light auf Team Pro werden bei den ankommenden anrufen unter user nur noch die Gruppen angezeigt.

Unter light konnte man die Endpunkte auswerten.

Ein grosser Punkt, warum wir SipgateIO nutzen ist der dass man nun eine relativ saubere Information produzieren konnte, welch Kollegen besetzt sind und welche nicht.

Ein ankommender Anruf sollte eigentlich beide Infos enthalten:
Im status ringing:  user (bei wem es alles klingelt), nebenstelle (Zentrale, Support,...)
Im status calling sollte nun user auf die endstelle geändert werden und nebenstelle gleich bleiben.

Nebenstelle könnte man natürlich auch mit der internen nummer abgleichen, jedoch den engerätenamen kann ich nun gar nicht mehr bekommen.

**Comment by fnordian** [comment]
Kannst Du mir bitte ein paar Details an marcus@sipgate.io schicken?

**Comment by merlink01** [comment]
Done :-)

**Comment by merlink01** [comment]
Den Grund des Problems habe ich inzwischen erkannt:
Dadurch, dass warteschleifen eingeführt wurden, geht bei eingehenden Anrufen immer die Warteschleife dran. z.B. Zentrale.
Nachdem aber eine Weitergabe von (Warteschleife Zentrale) --> (Endstelle) nicht signalisiert wird, kann man die Endstellen nicht herausbekommen.

Dies hatte ich an Markus geschrieben, aber leider bis heute keine Rückmelung erhalten.

**Comment by TheCK** [comment]
Sorry für die späte Antwort hier.

Aber wie Marcus die ja schon persönlich geschrieben hat ist es etwas komplexer das über die Warteschleife abzubilden. Ich würde das Issue hier erstmal schließen, wir haben das Problem aber noch auf dem Schirm.

**Comment by merlink01** [comment]
OK, perfekt.
