### ISSUE TITLE
team: Play-Ansagen defekt, in SQ funktionierend

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#67]
`<Play>` erfordert laut README.md ein 8 kHz gesampeltes wav file. Dieses funktioniert in Simquadrat, aber nicht in team: Hier erhalte ich bei Übergabe desselben in SQ funktionierenden .wav eine bis zur Unverständlichkeit verzerrte Ansage, die laut brummt. Im team-GUI lassen sich Ansagen in .mp3 und .ogg hochladen, .ogg funktioniert jedoch auch nicht per `<Play>`.

Es wäre gut, wenn `<Play>` .ogg ohne 8 kHz-Limitierung unterstützen würde, damit man auch hier Ansagen in HD-Qualität einspielen kann.

**Comment by fnordian** [comment]
Tritt das Problem weiterhin auf? Wir konnten es nicht reproduzieren.

**Comment by danielberlin** [comment]
Habe Details per Mail geschickt.

**Comment by danielberlin** [comment]
Gelöst.
