### ISSUE TITLE
Integration of multiple sipgate.io clients

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#69]
It is nice to see that current sipgate.io implementations let a kind of sipgate.io feature store grow (https://www.sipgate.io/de/solutions).

How would I be able to use several sipgate.io-capable clients at the same time? I can only configure one push URL at the moment.

One solution would be to have a wrapper script that runs on my server. In that script I could configure all URLs and an incoming pushs from sipgate.io would lead to a new push initiated by the wrapper to each configured sipgate client.

The other solution would be to enter several URLs directly and have the sipgate.io server done multiple pushs – especially if the pushs go to different servers, for example when I use one script on my own server but simultaneously also want to integrate a sipgate.io capable CRM which runs on the hoster's server (because they don't provide me the source code and/or only host it themselves due to their business model). The CRM would be the main application but it might not be capable of e.g. individually redirecting calls so my own scripts are still needed for that functionality.

Is sipgate.io also available for sipgate.co.uk customers soon or is this not planned?

**Comment by TheCK** [comment]
We haven't really thought about all the implications for suppling several URLs. E. g: what do we do when both destinations send back different xml answers? So at the moment this is not supported, and if you really need this functionality, you have to build it for yourself.

sipgate.io is currently only available for sipgate team users in co.uk but not for basic users.

**Comment by merlink01** [comment]
We did it by logging all events to an online webserver inside a Mysql database.
After this we could work with different clients on this DB.

**Comment by findingmarbles** [comment]
Wie von @merlink01 demonstriert, gibt es Workarounds. Wir werden erstmal nicht umsetzen.

LG, Co
