### ISSUE TITLE
Leerer "user" Parameter bei Voicemail "Answer" Event

### ISSUE THREAD

**Issue by bagsik** [sipgate/sipgate.io#70]
Wenn ich einen Anruf per .io an meine Voicemail weiterleite ist im "Answer" Event der Parameter "user" leer.
Kann man dort eventuell der Vollständigkeit halber den Wert "Voicemail" mitsenden?

**Comment by danielberlin** [comment]
Kann ich bestätigen. Statt leerem String wäre das wirklich besser.

**Comment by merlink01** [comment]
Selbes Problem bei Annahme durch die Warteschlange.

**Comment by bagsik** [comment]
Gibt es eine Planung, wann dies geändert wird?

**Comment by danielberlin** [comment]
Im Prinzip sind alle Situationen betroffen, wenn der Anruf nicht durch mich persönlich (sprich den primären Empfänger) angenommen wird, in team sogar auch, wenn ein meinem Benutzer hinzugefügtes externes Telefon (externe Nummer) statt VOIP-Telefon/sipgate SIM dieses Benutzers den Anruf annimmt.

**Comment by merlink01** [comment]
Das Problem, das Kunden die von einer Warteschlange angenommen werden und dann wieder auflegen ohne mit einem Mitarbeiter gesprochen zu haben als "Normal Angenommenes Gespräch" gekennzeichnet werden würde ich als Kritischen Bug bezeichnen.

Diese Kunden gehen ev. verloren, wenn man dies nicht erkennt und diese zurückrufen kann.

Ich habe diesbezüglich bereits mit Sipgate Entwicklern Kontakt und dieser schreibt am:

"""ich habe noch keine Infos, wann die API dies anbieten wird. Alternativ bietet sipgate zusätzlich zur API auch noch Presence per RFC3265 an. Damit ist es möglich, Presence-Informationen für einzelne Nutzer über die Kurzwahl zu subscriben. Dazu habe ich allerdings keine einfach zugängliche Dokumentation. Ein guter Startpunkt wäre, das Verhalten von Endgeräten wie z.B. dem Grandstream GXP2020 zu beobachten."""

Ich hoffe inständig, das hier nachgebessert wird.

**Comment by findingmarbles** [comment]
Nur kurz zur Info: Wir haben den Bug auf dem Schirm und er ist definitiv "to fix". Wir können leider noch nicht genau sagen wann.

**Comment by merlink01** [comment]
Gut zu hören, das ihr dran arbeitet.
Ich bin ansonsten sehr zufrieden mit SipgateIO.

Ich freue mich über Neuigkeiten.

**Comment by findingmarbles** [comment]
Hallo zusammen!

Wir haben den zweiten Bug behoben, der von @merlink01 mit den Warteschlangen. Neues Verhalten:

Der onAnswer-Event wird nicht mehr geschickt, wenn die Warteschlange drangeht, sondern erst dann wenn ein Mensch drangeht (oder die Voicemail, womit wir wieder beim ersten Bug wären). 

Beim onHangup Event steht allerdings immer noch 'angenommen' weil aus technischer Sicht ja jemand drangegangen ist. Für einen Anruf bei dem der Anrufer in der Warteschlange auflegt, fehlt der onAnswer-Event dann komplett. Geht ein Mensch (oder Voicemail) dran, gibt es onAnswer. So kann man die beiden Fällen unterscheiden. 

Die Lösung, dass der Hangup bei der Warteschleife trotzdem 'angenommen' im Hangup pusht, finden wir nicht so super schön. Wir haben mehrere Ideen, wie das aussehen könnte:

A) Hangup so lassen, dafür "Warteschlange drangegangen" auch signalieren; also 2 Answer-Events
B) Hangup-Event ändern, in "cancel"
C) Alles so lassen

Welches Verhalten erwartet ihr denn? A, B, oder C? Oder noch was anderes?

PS: Am Ursprungsbug mit der Voicemail sind wir noch dran.

**Comment by merlink01** [comment]
Super, Danke!!!
Ich werde drüber nachdenken.

**Comment by merlink01** [comment]
@findingmarbles gut zu hören, dass sich hier etwas tut.
Ich tendiere zu lösung "B". (The caller hung up before the called party picked up)
Das wäre meiner Meinung nach logisch gelöst.
Somit wäre die Warteschleife eigentlich nur ein "ringing" Status.

Eine Frage noch?
Wenn ein Mensch an die Warteschleife geht, wird dann bereits der User des Anschlusses übertragen, dem der Anschluss gehört. (per onAnswer-Event)
Nach meinen Tests stehen immer immer noch alle User aus dem ringing Status drin.

**Comment by merlink01** [comment]
OK, der User wird korrekt übertragen.

Danke!

**Comment by fnordian** [comment]
Wir machen das mit dem Cancel. Das Deployment ist gerade im Gange. Bitte mal testen ;-)

Vielen Dank für's Feedback.

**Comment by merlink01** [comment]
Hallo fnordian,

danke für die Rückmeldung.

Bis heute konnte ich noch keine Veränderung feststellen.

Hier ein Beispiel:
Timestamp: 18:17:52 30.11.2015
ID: 8356221846940759000
Status: normalClearing

Vielen Dank.

**Comment by fnordian** [comment]
Hi Merlink01,

Unter der CallId habe ich keinen Call gefunden, wohl aber unter einer, die sehr ähnlich ist. Könntest du beim nächsten Mal die korrekte, oder um ein paar Stellen verkürzte angeben, das spart viel Zeit ;-)

Das Cancel-Verhalten ist bis jetzt nur für die Warteschlange implementiert, nicht für die Voicemail. Da bin ich mir gerade nicht so sicher, ob das Verhalten so nicht doch in Ordnung ist. Schließlich ist die Voicemail ja ran gegangen. Dass das user-Feld fehlt, haben wir auf dem Schirm.

**Comment by merlink01** [comment]
OK, ja der war ausserhalb der Arbeitszeit.

Danke.

**Comment by fnordian** [comment]
Anrufe, die von der Voicemail angenommen werden, haben im Answer-Event jetzt user=voicemail.

Damit sollten alle Punkte des Tickets erledigt sein, oder?
