### ISSUE TITLE
Unbekannter Hangup Grund

### ISSUE THREAD

**Issue by bagsik** [sipgate/sipgate.io#71]
Habe im Event "hangup" im Parameter "cause" den Wert "chanunavail".
Was bedeutet dieser?

**Comment by wiesson** [comment]
Das bedeutet, die angerufene Nummer existiert nicht. Wir haben diesen Fall im Hangup nun um den Wert "notFound" erweitert (Siehe https://github.com/sipgate/sipgate.io/commit/9b1c91964792d7222911a3d50bb6c784bac66b99).

Bitte noch einmal testen.

**Comment by bagsik** [comment]
Danke.
"notFound" wird übermittelt
