### ISSUE TITLE
HangupCauses: notFound/notAnswer statt congestion

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#73]
Ergänzend zu #71 habe ich jetzt folgendes beobachtet:

1. Anruf auf 01579 ergibt zwei Minuten lang ein Freizeichen, dann meldet sipgate.io bei beiden `notFound`.
2. Erneuter Anruf nach Abschalten des Endgeräts ergibt `notFound` bei mir und `noAnswer` beim Angerufenen.

Fazit: `congestion` taucht nun gar nicht mehr auf, auf jeden Fall aber ist `noAnswer` falsch wenn abgeschaltet.

**Comment by danielberlin** [comment]
Besteht die Möglichkeit, mir die Labelzuweiseberechtigung zu erteilen? :)

**Comment by findingmarbles** [comment]
Hi Daniel! 

Danke für die Beobachtung! Die Hangup-Causes werden an verschiedenen Stellen behandelt, an denen wir verschiedene Infos zur Verfügung haben. Wir denken daher darüber nach, die Hangup-Causes zu vereinfachen, damit Anrufer und Angerufene nicht verschiedene Causes gepusht bekommen. 

Stay tuned :)

Corinna

PS: Wir möchten gerne die Label-Macht bei uns im Team belassen. Ich hoffe, Du verstehst das.

**Comment by findingmarbles** [comment]
Wir werden es erstmal so lassen wie es ist.
