### ISSUE TITLE
Migrierter basic-Account: from enthält SIP-ID statt Telefonnr.

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#74]
Bei einem vom alten basic auf das neue migrierten Account übermittelt sipgate.io als `from` die SIP-ID an Stelle der vollständigen Absenderrufnummer bei ausgehenden Telefonaten. Das lässt sich zwar selbst beheben, indem man "e0" an die SIP-ID auf allen Endgeräten anhängt, aber wer kommt schon darauf? Und die alte SIP-ID funktioniert ja weiter...

Im Vergleich zu einem im neuen basic angelegten frischen Account fehlt im migrierten basic-Account übrigens auch das Feature "Ortsrufnummer" (obwohl die Ortsrufnummer mitmigriert wurde und auch funktioniert).

**Comment by danielberlin** [comment]
Vgl. #52

**Comment by findingmarbles** [comment]
Bitte nochmal testen, sollte jetzt behoben sein :)
