### ISSUE TITLE
Kleiner Bug bei der Internen Telefonie

### ISSUE THREAD

**Issue by merlink01** [sipgate/sipgate.io#76]
Wenn Intern angerufen wird, werden 2 Anrufe Signalisiert.

Ein Ausgehender und ein Eingehender Anruf.
-Beim Ausgehenden Anruf wird im Status Ringing und onAnser der User des Ausgehenden Anrufers übermittelt. (Korrekt)

-Beim Eingehenden Anruf wird im Status Ringing der User des Ausgehenden Anrufs angezeigt. (Falsch)
Sobald der Eingehende das Gespräch annimmt wird der User des Eingehenden Anschlusses angezeigt. (Korrekt)

Hier sollte der Eingehende User auch im Ringing Status angezeigt werden.
Nicht kritisch aber "unschön" :-)

**Comment by findingmarbles** [comment]
Hi merlink01!
Werden wir uns auch angucken. 
LG, Co

**Comment by TheCK** [comment]
Hallo @merlink01 ,

das Problem sollte jetzt behoben sein. Bitte nochmal testen.

**Comment by merlink01** [comment]
Ja, der Fehler is gefixt ;-)
