### ISSUE TITLE
Bug: User wurde bei onAnswer nicht übermittelt

### ISSUE THREAD

**Issue by merlink01** [sipgate/sipgate.io#77]
Bei einem einkommenden Anruf wurde anscheinen der User nicht korrekt übermittelt.

id: 3953568025114733600
timestamp: 23.11.2015, 10:53:32

Der Anruf wurde angenommen, jedoch wurde nur der Name der Gruppe übermittelt, nicht der Name der Endstelle.

Könnten Sie das mal checken?

Vielen Dank.

**Comment by wiesson** [comment]
Können Sie mir bitte eine kurze Email an support@sipgate.io mit Ihrer Kundennummer senden?

**Comment by merlink01** [comment]
OK, habs nun analysiert: Die User Variable enthät nur User und keine Nebenstellen.

Somit ist das vehlten Korrekt.

Closed!
