### ISSUE TITLE
Bug: User werden bei überschwappenden Gesprächen nicht aktualisiert

### ISSUE THREAD

**Issue by merlink01** [sipgate/sipgate.io#78]
Wir haben die Einstellung, dass bei klingelnden Anrufen auf den Vertrieb nach 30 Sekunden überschwappt.

-Somit klingelt der Anruf die ersten 30 Sekunden nur bei Vertriebsmittarbeitern.
Diese Tauchen in der User Variablen auch auf. [Korrekt]

-Nach der besagten Zeit wird der Kunde an die komplette Zentrale weitergegeben, falls kein Vertriebsmitarbeiter ran gegangen ist.
Zu diesem Zeitpunkt sollte die Uservariable aktualisiert werden, jedoch werden Momentan noch die selben User von der Vertriebsgruppe übermittelt. [Fehler]

Vielen Dank.

**Comment by findingmarbles** [comment]
Hi merlink01!
Werden wir uns angucken. 
LG, Co

**Comment by TheCK** [comment]
Hi @merlink01,

Ich konnte das Problem leider nicht nachstellen. Besteht es denn noch? Wenn ja. Wie ist denn die Weiterleitung konkret eingestellt. Ist das Benutzer auf Gruppe, oder andersrum? Am besten mit einem konkreten Beispiel an karsten@sipgate.io

Grüße,
Karsten

**Comment by merlink01** [comment]
Hallo @TheCK ,

das Gespräch geht auf der Gruppe "Vertrieb" ein und wird nach 20 Sekunden auf die Gruppe "Zentrale" umgeleitet.

Also Gruppe --> Gruppe.

Nachdem ich mich mit der API noch einmal auseinandergesetzt habe (ich programiere gerade ein Webinterface in Python mit SQL und xmlrpc) habe ich auch keine logische Lösung gefunden wie ihr dieses mit den vorhandenen Funktionen abbilden könntet.

Die Funktion Newcall kann man nicht nutzen, da dieses Gespräch ja kein neuer Call im Sinne von ist.
Die Funktion Answer kann man nicht verwenden, da niemand ran gegangen ist.

Natürlich könnte man den Ersten Call als beendet markieren und danach einen neuen erstellen, jedoch wäre dies keine schöne Lösung.
Ich würde empfehlen, bei weiterleitungen einen neuen Befehl zu etablieren:
"event=routing&callId=123456&user=John+Doe"
Somit würde der Status ringing erhalten bleiben.

Sorry für die späte Antwort.

Merlink

**Comment by merlink01** [comment]
Leider bis dato keine Rückmeldung auf diesen Eintrag noch auf die E-Mail.

Wie ist denn hier der Status?

**Comment by CookieCrumb23** [comment]
Hallo @merlink01 ,
wir haben uns das jetzt nochmal genauer angeschaut und leider ist das Ganze technisch nicht ganz so einfach zu lösen. Wir würden uns eine schlaue Lösung ausdenken, aber das würde nicht in absehbarer Zeit passieren.

Wir behalten das auf dem Schirm, würden dieses Issue aber erstmal schließen.

Grüße
Daniel
