### ISSUE TITLE
team: Telefone ohne Benutzer nicht io-fähig

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#79]
Hi,

momentan kann man in team Telefone ohne Benutzer (https://secure.live.sipgate.de/settings/setup/unlinked) unter https://secure.live.sipgate.de/settings/sipgateio nicht aktivieren, d.h. diese Anrufe kann man nicht über io verarbeiten.

**Comment by JHGitty** [comment]
Sollte unbedingt behoben werden!

**Comment by findingmarbles** [comment]
Haben wir auffem Schirm. Kann aber noch etwas dauern.
