### ISSUE TITLE
Variable für Status bei SIMquadrat Handy

### ISSUE THREAD

**Issue by Harald2** [sipgate/sipgate.io#80]
Ich nutze sipgate.io für eine Kunden Hotline per SIMquadrat (also Handy). 
Es funktioniert wunderbar und kann per PHP komplett gesteuert werden. Super Sache!

**Leider vermisse ich eine Funktion, die den Status von dem Handy an das Script zurück gibt.**
Es müsste möglich sein, festzustellen ob das Telefon eingeschaltet oder überhaupt in das Netz eingebucht ist und darauf Schlüssel für eine Ansage zu gestalten oder es weiterzuleiten.

Derzeit werden Gespräche, die während eines Funklochs ankommen abrupt beendet, weil ich keinen Anrufbeantworter aktiv haben kann.

Wäre es möglich den Status des Handys als Variable zur Verfügung gestellt zu bekommen?

Oder habt Ihr hier eine bessere Lösung parat an die ich noch nicht gedacht habe?

**Comment by danielberlin** [comment]
Soweit ich es in Erinnerung habe, geht die Voicemail bei "nicht ins Netz eingebucht" (Funkloch) direkt ran, auch und gerade wenn verzögerte Annahme (25 s) aktiviert ist. Das sollte für das Szenario schon helfen, oder? Wenn ich es richtig verstanden habe, soll die Voicemail nur im Falle eines Funklochs ran, um so viele Anrufe wie möglich persönlich entgegennehmen zu können.

**Comment by Harald2** [comment]
Ich will überhaupt keine Voicemail verwenden. Da sprechen Kunden leider immer drauf obwohl man sagt, dass die Mailbox nicht abgehört wird. Ich würde gerne je nach Situation die richtige Voice Nachricht abspielen oder halt mit einer Weiterleitung reagieren.

Z.B. will ich je nach Uhrzeit an eine andere Rufnummer weiterleiten oder halt weiterleiten wenn das Handy nicht erreichbar ist oder Besetzt ist. Derzeit geht dies alles nicht. Weiterleiten geht nur nach x Sekunden aber hilft mit nicht, weil die Regeln in sipgate.io definiert werden müssten und nicht in dem Weiterleitungs Interface.

Das Shopfeature Weiterleitung würde ich halt gerne in Sipgate.io für die Programmierung zur Verfügung haben. 

Alternativ das Feedback per Variable ob das Handy eingeschaltet, besetzt ist oder nicht. 
Das kann man allerdings auch gut für das Festnetz verwenden, denn auch die Sipgate Basic Festnetztelefone können nicht verbunden oder besetzt sein.

**Also solch etwas wie:**
Anruf annehmen Ziel A
Wenn Ziel A besetzt => Ansage und Weiterleiten an Ziel B
Wenn Ziel A ausgeschaltet ist => andere Ansage und Weiterleiten an Ziel C
Wenn Ziel A Eingeschaltet ist und niemand nach 25 Sek. ran geht => andere Ansage und Weiterleiten an Ziel D.

**Comment by danielberlin** [comment]
Das skizzierte Szenario gefällt mir gut und das würde ich auch gebrauchen können. Mal in sipgate.io ausgedrückt:

```xml
 <Response>
  <IfBusy>
    <Play>https://mein.server/ansage1.wav</Play>
    <Dial><Number>49170123455</Number></Dial>
  </IfBusy>
  <IfUnreachable>
    <Play>https://mein.server/ansage2.wav</Play>
    <Dial><Number>49171998877</Number></Dial>
  </IfUnreachable>
  <IfNoAnswer delay="25">
    <Play>https://mein.server/ansage3.wav</Play>
    <Dial><Number>49171998899</Number></Dial>
  </IfNoAnswer>
</Response>
```

Alternativlösung (workaround) ohne die Ansagen:

Du konfigurierst bei Simquadrat den Parallelcall auf eine Sipgate basic Nummer und gibst dort per sipgate.io uhrzeitabhängig entweder ein `Reject` (Szenario Anruf annehmen Ziel A, der Zweitanruf wird ohne jegliches Klingeln abgewiesen, aber die Hauptnummer, d.h. SQ-SIM, klingelt weiter) oder eben keines zurück.

Fallweise Rufumleitung bei 'besetzt' und 'Telefon nicht am SIP-Server angemeldet' gab es im alten Sipgate basic schon jahrelang im Web-GUI, das per sipgate.io oder wenigstens im neuen Dashboard anzusteuern sollte also nicht allzu aufwändig sein.

Die Weiterleitung nach 25 s (o.g. Szenario 4) dann eben über das Weiterleitung-Feature (ohne Ansage sollte ja auch nicht so schlimm sein).

**Comment by Harald2** [comment]
Vielen Dank.
Ich hätte es nicht besser ausdrücken können!!!
Gerade die Ansagen machen einen deutlichen Mehrwert, da diese auf die Situation reagieren und ggf. eine Ansage kommt, in der der Kunde gebeten wird ein anderes Mal anzurufen. Z.B. wenn ich gerade telefoniere.


Der Workaround wäre theoretisch machbar. 
Muss ich mal versuchen nachzustellen.
Allerdings kommt bei Anruf eine Ansage, die das Gespräch so aussehen lässt, als wenn jemand ran gegangen wäre. Wie ich darauf reagieren sollte es bedingt weiterzuleiten muss ich nun testen.

**Comment by findingmarbles** [comment]
Leider haben wir die Infos, ob ein Handy im Netz oder nicht, nicht in Echtzeit. Daher können wir das leider nicht umsetzen. Sorry!
