### ISSUE TITLE
Parallelcall und Weiterleitung behandeln

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#82]
Es ist von essenzieller Bedeutung, auch Parallelcall und Weiterleitung per io steuern zu können. Zumal im Gegensatz zu der früher sekundengenau einstellbaren Weiterleitung auf der neuen basic-Plattform nur noch zwei recht sinnfreie Optionen sofort oder 25 s (da haben die meisten schon aufgelegt) möglich sind. Das haben auch einige im Feature Store kritisiert (https://www.simquadrat.de/feature-store/weiterleitung). Dann bitte wenigstens 25 s auf 20 s oder 15 s heruntersetzen.

Wenn man das mit io steuern könnte, wäre es natürlich die ideale Lösung:

* Parallelcall:

```
<Response>
  <ParallelCall>
    <Dial>49171234567</Dial>
    <Dial>49179998877</Dial>
  </ParallelCall>
</Response>
```
Sehr praktisch wäre zudem, wenn auch mehr als zwei Nummern parallel gingen, z.B. aus Privatkundensicht Festnetz, Handy UND Handy eines Familienmitglieds – dann verpasst man keinen wichtigen auf der Festnetznummer (oder auf dem gerade wegen Funkloch nicht erreichbaren Simquadrat-Handy, Funklöcher gibt es gerade im Altbau etc. noch genug) eingehenden Anruf mehr.

* Weiterleitung zeitgesteuert (z.B. nach 10s)
```<Response><Dial delay="10"><Voicemail/></Dial></Response>```

 * Am Anfang im allerersten Simquadrat-Dashboard gab es mal unter Weiterleitung (und m.W. auch Parallelcall) eine zusätzliche Checkbox "Bei Nichtannahme auf Voicemail", d.h. zuerst wird der Parallelcall bzw. die Weiterleitung versucht, und wenn auch da niemand abnimmt, geht der Anruf auf die Voicemail.

Das könnte so aussehen:

```
<Response>
  <ParallelCall>
    <Dial>49171234567</Dial>
    <Dial delay="10"><Voicemail/></Dial>
  </ParallelCall>
</Response>
```

49171234567 klingelt sofort und nach 10 Sekunden greift die Voicemail.

**Comment by JHGitty** [comment]
:+1: Klingt gut, sollte man umsetzen.

**Comment by findingmarbles** [comment]
Haben wir auffem Schirm. Wollen wir langfristig machen, hat aber niedrige Prio. Daher schliessen wir das Ticket erstmal.

**Comment by fnordian** [comment]
Zumindest Parallelcalls bei eingehenden Anrufen ist jetzt implementiert:

<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial>
        <Number>4915799912345</Number>
        <Number>492111234567</Number>
    </Dial>
</Response>

**Comment by danielberlin** [comment]
Super, ein Meilenstein würde ich sagen!
Früher gab es doch Releases und die sogar mit Namen, wird das nicht mehr weitergepflegt?

**Comment by danielberlin** [comment]
Wie genau ist es denn gedacht, um nicht nur eine multiple Weiterleitung eingehender Anrufe zu erreichen (Anruf wird auf mehrere externe Nummern weitergeleitet, aber klingelt an dieser Stelle nicht)?

Mein Hauptanwendungsfall: Bestimmte eingehende Anrufe selektiv parallel auf einem zweiten Telefon klingeln zu lassen. Also keine Weiterleitung des Anrufes an zwei externe Nummern, sondern auch Klingeln auf der vom Anrufer gewählten Nummer.

* Dann müsste ich, wenn ich es richtig sehe, die eigentlich angerufene Nummer nochmal explizit mit `<Number>` mitwählen? Dann erhalte ich auf dieser zwei Pushs, so dass sich insgesamt, mit zweimal `<Number>`, drei eingehende Pushs ergeben?

* Die Tarifierung sollte sich dann ja genauso verhalten wie beim Parallelruf-Feature, d.h. nimmt man den Anruf am lokalen Endpunkt an, sollte es nichts kosten. Für z.B. Simquadrat wäre es hier noch wichtig zu wissen, welche Nummer (Orts- oder Mobilnummer) ich am Besten angebe für das Mitklingeln der SQ-SIM aus tariflichen Gesichtspunkten.

* Für dieses Szenario stimmt momentan die bei den weitergeleiteten Anrufen gesetzte `diversion`-Nummer nicht, höchstwahrscheinlich hat das direkt mit #244978 zu tun. Das verkompliziert die Erkennung, insbesondere hatte ich direkt einen Call-Loop (Vervielfachung eines eingehenden Calls), den ich an Hand von `diversion`erkennen und ausschließen muss.

Ausgehender Parallelcall wäre auch sehr gut, kommt sicher noch? 😀

In Sipgate team könnte man mit ausgehendem Parallelcall übrigens sehr praktisch ad-hoc Gruppen konfigurieren, z.B. an Hand bestimmter weiterer Parameter Gruppen dynamisch zusammenstellen.
