### ISSUE TITLE
Ändern der Absender-Rufnummer

### ISSUE THREAD

**Issue by JHGitty** [sipgate/sipgate.io#83]
Sipgate unterstützt das Ändern der Absender-Rufnummer. Kann diese auch über die API geändert werden?

**Comment by findingmarbles** [comment]
Ja, das geht: https://github.com/sipgate/sipgate.io#dial
Beispiele 3 und 4 sind Dein Freund.

LG, Co

**Comment by danielberlin** [comment]
Ich denke, der OP fragte explizit nach der REST API (http://www.live.sipgate.de/api/rest), Deine Antwort bezieht sich aber auf sipgate.IO (auch eine API, aber nicht "die" API).

**Comment by JHGitty** [comment]
@danielberlin Mir teilte der Support per Email mit, dass es keinen technischen Support mehr für die REST API gibt. Entsprechend kann ich nur nach Sipgate.IO fragen.

**Comment by findingmarbles** [comment]
@JHGitty Löst meine obige Antwort denn Dein Problem?

PS: Um die Verwirrung komplett zu machen: Wenn irgendwo "die sipgate API" auf sipgate Seiten steht, meinen wir unsere [XML-RPC API](http://teamhelp.sipgate.de/hc/de/articles/203651121-Was-ist-die-sipgate-API-und-welche-Funktionen-bietet-sie-) und nicht die REST API. Mit der XML-RPC API kann man die Absender-Nummer leider auch nicht setzen.

**Comment by JHGitty** [comment]
@findingmarbles Ich konnte es noch nicht austesten, da ich leider noch keine Zeit dafür finden konnte. Sofern man in der ``Dial`` Methode die ``callerId`` ändern kann, so wie es auch übers Webinterface möglich ist, entspricht dies meinen Wünschen. :+1: 

Ich würde mich natürlich auch zusätzlich darüber freuen diese Funktion in der XML-RPC API zu sehen, d.h. dass ich die Absender-Rufnummer generell über die API im Account ändern kann bzw für einzelne Anrufe ändern kann. Entsprach zwar nicht meiner ursprüngliche Nachfrage, aber das wäre generell auch praktisch.

**Comment by danielberlin** [comment]
@JHGitty `<Dial callerId="49170123">4987654</Dial>` funktioniert einwandfrei.
