### ISSUE TITLE
Anbindung an Jira Service Desk

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#84]
Gibt es schon eine Anbindung an Jira Service Desk (https://de.atlassian.com/software/jira/service-desk)?

Denkbar wäre z.B. ein Jira Plugin Modul (https://developer.atlassian.com/docs/getting-started/plugin-modules) mit folgender Funktionalität:

1. Ein eingehender Anruf auf der Supportdurchwahl sucht nach Vorhandensein der Anrufernummer und öffnet ggf. direkt das letzte Ticket bzw. bei mehreren eine Ticketübersicht
2. Falls der Anrufer nicht bekannt ist, wird ein neues Ticket geöffnet und die Nummer des Anrufers automatisch eingefügt (neues Feld Anrufer).

Wer hier eine Lösung oder Interesse hat, den bitte ich um Nachricht, damit man ggf. Synergien nutzen kann, falls wir ein solches Plugin entwickeln werden.

**Comment by findingmarbles** [comment]
Hi Daniel!

Die Anbindung gibt es noch nicht. Falls ihr eine baut, featuren wir euch gerne auf unserer Lösungsseite: 
http://dev64-247.sipgate.io:10080/de/solutions

Genau dafür ist sie da :)

LG, Co

**Comment by JHGitty** [comment]
@danielberlin Auch wir haben Jira im Einsatz. Ist dir eine Lösung bekannt, wie man eine bestimmte Ticket-Seite öffnet könnte, eventuell eine API oder dergleichen? Spontan fällt mir nicht ein wie man das einfach lösen könnte.

Stellst du dir das vorstellst. Via Javascript direkt als JIRA Plugin? Oder eine Desktop-Anwendung, welche im Standard-Browser automatisch die entsprechende JIRA Ticketseite öffnet?

**Comment by BlackMac** [comment]
Schaut mal hier, vielleicht hilft das.

https://sipgatesocket.herokuapp.com/

Disclaimer: Das ist weder fertig noch funktioniert alles, aber die Idee sollte rüber kommen.

**Comment by danielberlin** [comment]
Ich stelle mir das als JIRA Plugin vor. Das genannte Sipgatesocket sieht wie geschaffen dafür aus. :smile:

Kurzfristig werden wir hierfür nichts entwickeln, aber falls hier noch mehr Leute interessiert sind, könnte man das nochmal überlegen. Falls jemand Erfahrung in der Entwicklung von JIRA Plugins hat, könnte ich mir gut vorstellen, dass wir dafür sipgate.io Expertise bereitstellen, aber für die eigene Entwicklung eines Plugins fehlt momentan leider die Zeit. Mittel- bis langfristig sieht das jedoch anders aus.

**Comment by danielberlin** [comment]
Es gibt brandaktuell ein neues Zapier Addon für Jira: https://marketplace.atlassian.com/plugins/com.atlassian.jira.plugins.zapier/cloud/overview

Um das Rad nicht neu zu erfinden, wäre die Anbindung von sipgate.io an Zapier nützlich. Ich möchte das an dieser Stelle zunächst für andere Interessierte festhalten und darauf später zurückkommen, kurzfristig werden wir hier nichts machen.

**Comment by LittleNo** [comment]
Dann grabe ich dieses Thema mal aus, weil ein sipgate.io-Plugin (oder sonstige Anbindung) für Jira fände ich auch super
