### ISSUE TITLE
feature request: sipgate.io API

### ISSUE THREAD

**Issue by philkunz** [sipgate/sipgate.io#85]
The current concept of the sipgate.io API actually only allows sipgate to initiate action (send a request) for inbound calls where a sipgate customer hosted server responds to it.

Are there any plans to allow the other way round to initiate outbound calls?

This would be very useful to implement things like phone based twostep authentication for web services.

**Comment by findingmarbles** [comment]
Sounds like an interesting use case. Could you write us at support@sipgate.io and go a little into detail on what you'd like to implement? Maybe we can help.

**Comment by danielberlin** [comment]
Outbound calls should be possible via Sipgate Samurai API:

DE: http://www.sipgate.de/img/sipgate_api_documentation.pdf
EN: http://book.sipgate.io/content/click2call.html

http://teamhelp.sipgate.de/hc/de/articles/203651071-Beispiele-für-die-Verwendung-der-sipgate-API
