### ISSUE TITLE
Gather funktioniert nicht bei mir

### ISSUE THREAD

**Issue by askeron** [sipgate/sipgate.io#86]
Hi,

ich habe einen kleinen node.js server geschrieben, um die Gather-Funktionalität zu testen. Der Plan war, dass jemand meine Sipgate-Nummer anruft, dann automatisch abgenommen wird, demjenigen eine Ansage abgespielt wird und er dann immer wieder Nummer eintippen kann, dann wieder eine Ansage hört, dann wieder Nummern eintippt, etc.

Doch leider wird nie abgenommen, wenn ich anrufe. Im Log taucht leider garnichts auf, ich sehe aber dass Requests reinkommen.

Details:
Als URL für eingehende Anrufe ist `http://99b27dac.ngrok.io/newCall` eingestellt.
Wenn ich die Telefonnummer anrufe geht folgender Request bei mir ein:

```
POST /newCall HTTP/1.1
Accept: application/xml, text/plain, text/html
Accept-Charset: utf-8
User-Agent: sipgate.io
X-SIPGATE-JOBS: http://www.sipgate.de/jobs
Content-Length: 117
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Host: 99b27dac.ngrok.io
Accept-Encoding: gzip,deflate
Via: 1.1 localhost (squid/3.1.20)
X-Forwarded-For: 212.9.44.148
Cache-Control: max-age=259200
X-Forwarded-For: 217.116.118.254

event=newCall&direction=in&from=491723479XXX&to=4922167770XXX&callId=73366644794603XXXXX&user%5B%5D=XXXXX+XXXXX
``` 
(ein paar Daten sind am ende mit X-en überschrieben, dient der Anonymisierung)

Darauf hin wird folgende Response ausgeliefert:
``` 
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather onData="http://99b27dac.ngrok.io/dtmf" maxDigits="1" timeout="10000">
        <Play>
            <Url>http://99b27dac.ngrok.io/test.wav</Url>
        </Play>
    </Gather>
</Response>
```
mit 200 OK - 202 bytes application/xml; charset=utf-8

Darauf hin wird dann auch direkt noch die referenzierte `http://99b27dac.ngrok.io/test.wav` per GET abgerufen, und danach passiert nichts mehr. Es klingelt einfach weiter, der Anruf wird nicht angenommen und ich bekomme keine Ansage. Und es gibt keinen Eintrag im Log.

**Comment by fnordian** [comment]
Magst du nochmal testen? Ich habe einen Fehler behoben.

**Comment by askeron** [comment]
Hi @fnordian,

danke, jetzt funktioniert es. Allerdings die angegebene Play-Url aus der newCall-Response nicht abgespielt. D.h. aus Sicht des Nutzers fehlet die Ansage vor der ersten Zahleneingabe.

Außerdem habe ich gesehen, dass wenn der nutzer während eines Gathers auflegt, ihr nochmal einen dtmf-Request mit `dtmf=-1` schickt. Das ist super so, sollte dann aber auch in die Doku.

Vielen Dank schonmal und VG

**Comment by danielberlin** [comment]
Diese `dtmf=-1`mit Wert minus 1 habe ich auch beobachtet, aber während des noch aktiven Gatter-Anrufs. Sind vermutlich irgendwelche Störgeräusche, die in Töne umgewandelt werden?

Ansonsten – wie hast Du denn das in der `Play`-URL übergebene Soundfile generiert? Wenn es nicht den Vorgaben entspricht, ist beispielsweise bei mir lautes Brummrauschen zu hören...

**Comment by askeron** [comment]
Ich habe die wav-Datei über den TTS-Service von @fnordian generieren lassen (http://46.101.116.223:8080/?text=Test), daher sollte die korrekt sein. Außerdem ist es die gleich wav-Datei, die auch nach der Nummereingabe als Play-Url angebe, und an dieser Stelle höre ich sie im Telefon, nur halt nicht vor der ersten Nummerneingabe.

**Comment by fnordian** [comment]
@askeron tritt das Problem immernoch auf? In meinen Tests mit dem gleichen Soundfile und XML funktioniert alles wie erwartet.

**Comment by askeron** [comment]
Ja, das Problem besteht noch, aber ich weiß jetzt was passiert. Bei der ersten Play-Url wird der Anfang des Soundfiles abgeschnitten. Daher wurde die sehr kurze Nachricht "Test" auch geschluckt. Ich habe die Play-Url jetzt mit einem neuem wav-File ausgetausch, dass ich unter der URL http://46.101.116.223:8080/?text=Okay%20this%20is%20now%20an%20even%20longer%20message%20to%20test%20if%20the%20problem%20is%20that%20the%20old%20message%20was%20to%20short heruntergeladen habe.

Das Resultat war, dass ich wie bisher nach der ersten Nummerneingabe die volle Nachricht gehört habe, aber die Ansage vor der ersten Nummerneingabe fing mit "is now an even longer" an, d.h. das "Okay this" wurde verschluckt.

**Comment by danielberlin** [comment]
Die Ansagen werden generell auf allen Sipgate Plattformen (basic, team) oft verschluckt, z.B. bei der Tarifansage "Nur x Cent" höre ich an Snob-Geräten oft das "nur" nicht. Das trifft auch auf die erste Sekunde von Play-Files zu, kann ich also bestätigen.

**Comment by BastianS1986** [comment]
Mir ist aufgefallen, dass wenn ich z.B. ein Timelimit von 10 Sekunden setze, der Anrufer während des Abspielens der Sounddatei auflegt und der nächste Anrufer innerhalb des noch laufenden Limits anruft, keinerlei DTMF Eingaben angenommen werden.

Nach Ablauf des Timeouts bekomm ich dann den Request mit -1 zugeschickt.

**Comment by findingmarbles** [comment]
@BastianS1986 
Klingt komisch. Müssen wir hier mal nachstellen.

**Comment by BastianS1986** [comment]
Ich habe in letzter Zeit massiver das Problem, dass DTMF Eingaben nicht angenommen werden.
Als Gather-Request kommt folgendes von meinem Server:

<?xml version="1.0" encoding="UTF-8"?>
<Response onHangup="http://sipgate:simquadrat@simquadrat.computer-weinheim.de/simquadrat.php">
<Gather onData="xxx.php" maxDigits="1" timeout="1000">
<Play>
<Url>xxx.wav</Url>
</Play>
</Gather>
</Response>

Und wenn der Kunde eine Taste drückt kommt folgender Request:
event=dtmf&dtmf=-1&callId=xxx

Woraufhin mein Script natürlich nichts mehr auswerten kann.

Interessanterweise klappt es meist, wenn die betreffende Person auflegt und dann neu anruft.

Hier noch die Timestamps (für evtl. Debuggen)
Anruf des Kunden: Date: Wed, 20 Apr 2016 12:59:32 GMT
DTMF-Request: Date: Wed, 20 Apr 2016 13:00:06 GMT

**Comment by TheCK** [comment]
Hallo @BastianS1986,

sorry für die späte Antwort. Ich habe versucht, das Szenario mit den "hängenden" Gathers nachzustellen. Das ist mit allerdings nicht gelungen. Bei mir hat alles einwandfrei funktioniert.

Es wäre super wenn Du mir nochmal ein Beispiel zukommen lassen könntest. Am Besten mit Datum, Uhrzeit, A- und B-Rufnummer, und Sipgate.io Call-ID an karsten@sipgate.io
