### ISSUE TITLE
Fehlene Response im Log

### ISSUE THREAD

**Issue by DaSpors** [sipgate/sipgate.io#87]
Im sipgate.io Log fehlen mir die Responses wenn sie leer sind, also wenn der Server nur <Response/> zurückschickt. Das kann ja bei hangup durchaus sein.

**Comment by danielberlin** [comment]
Rein von der Spezifikation her solltest Du da auch gar nichts zurückgeben, denn bei Answer/Hangup wird ja nichts ausgewertet. Das finde ich so eher designkonform, da auch nichts anzuzeigen bzw. gar nicht erst auf Deine Antwort zu warten.

Answer/Hangup dient ja nur dazu, dass Du den Push erhältst und den Anruf auswerten kannst. Was würdest Du denn z.B. bei Hangup zurücksenden wollen, auch wenn es keine Bedeutung hat?

**Comment by DaSpors** [comment]
Uh...das hatte ich glatt übersehen. 
Momentan senden wir eigentlich nichts zurück, aber im Context von Issue #88 (also Sichtbarkeit für den Nutzer) könnte auch hier für den Nutzer eine Response vom dahinterliegenden System sinnvoll sein.
Sowas wie 'Ticket erstellt' oder 'X Notizen angelegt', je nachdem was im System während des Calls passiert ist.

**Comment by merlink01** [comment]
Ich bin auch dafür den Response auszugeben, auch wenn er in diesem Fall nicht ausgewertet wird.
z.B. hinterlege ich dort Errorcodes oder Tracebacks.

Ein Leeres Feld anzuzeigen, wenn ein Wert zurückgegeben wird halte ich für inkorrekt.

**Comment by TheCK** [comment]
Hallo @DaSpors und @merlink01,

Wie ich in #88 schon geschrieben habe, wollen wir diese Fehler nicht speichern. Wie ich auch geschrieben habe wird es in Zukunft möglich sein die URLs über eine API zu setzen. Damit kann dann der Kunde keine falsche URL mehr bei sicht eintragen.

Ich hoffe das hilft weiter.
