### ISSUE TITLE
Fehler vom Server zurückgeben

### ISSUE THREAD

**Issue by DaSpors** [sipgate/sipgate.io#88]
Wir nutzen einen Authentifizierungsmechanismus mittels Token, angehängt an die URL.
Es kann aber sein, dass ein falsches (oder serverseitig gelöschtes) Token eingesetzt wird.

Wie kann der Server in der <Response/> einen Fehler signalisieren?
Momentan geht das m.E. nur indem falsche XML Daten zurückgegeben werden?!

Weiterhin sollten Fehler irgendwo/-wie dem Nutzer sichtbar gemacht werden, sodass er reagieren kann. Zurzeit sieht man das nur im IO-Log, das ja aber auch deaktiviert sein kann.

**Comment by TheCK** [comment]
Hallo @DaSpors,

ich finde das eher schwierig und nicht auf unserer Seite aufgehoben.

Wir werden in (naher) Zukunft eine Rest-API anbieten, über die man die sipgate.io URLs setzen kann. Die Authentifizierung erfolgt dabei über OAuth2.0. Damit können dann für Kunden die URLs gesetzt oder bei abgelaufenen Tokens erneuert werden.

Ich hoffe, dass das das Problem löst?

**Comment by DaSpors** [comment]
Das kommt darauf an: Was heisst denn "in naher Zukunft"?

**Comment by DaSpors** [comment]
Grundsätzlich kann natürlich weiterhin ein falsches API Token hinterlegt sein (z.B. durch Invalidierung, Kompromitierung,...). Es ist also nur ein "sollte helfen", nicht eine wirkliche Problemlösung ;)

Langfristig sollte m.E. auch auf Ihrer Seite eine Signalisierung möglich sein.

**Comment by TheCK** [comment]
Nach momentaner Planung wird es noch im laufe dieses Monats fertig.

**Comment by DaSpors** [comment]
Gibt es schon was Neues zu der API?

**Comment by fnordian** [comment]
Tatsächlich wird es in Kürze etwas neues geben. Hast du Lust vorab zu Testen? Schreib mir kurz ne Mail an marcus@sipgate.io und ich schick Dir die Details schon heute.
