### ISSUE TITLE
Call_ids nicht einzigartig

### ISSUE THREAD

**Issue by merlink01** [sipgate/sipgate.io#90]
UnsereTelefonliste logt nun schon seit beginn von SipgateIO alle Anrufe mit.

In der Datenbank habe ich die Call_ID benutzt um einen Anruf eindeutig zuzuordnen.

Somit nutze ich diese ID als Primary Key in unserer SQL Datenbank.

Nun bekomme ich beim speichern mancher neuen Anrufe folgende Fehlermeldung:

IntegrityError: (1062, "Duplicate entry '525' for key 'PRIMARY'")

Somit ist diese Call_ID bereits in der Datenbank vorhanden und eine 100%ige Zuordnung eines Anrufes nicht mehr gewährleistet.

Wie kann man dieses Problem lösen?
Um eine Zuzordnung zu gewährleisten müssen Sie entweder:
1. Gewährleisten, dass die Call ID wie eine UUID einzigartig ist.
2. Zusätzlich eine UUID eines Anrufes mitsenden, welche eine Unterscheidung möglich macht.
3. an die CallID eine UUID anhängen, womit 1. gewährleistet wäre.

Ich hoffe auf eine baldige Antwort

**Comment by merlink01** [comment]
Nach weiterer Analyse habe ich nun herausgefunden, das sich die CallIDs verändert haben.

Früher war es ausreichent diese als Integer zu behandeln.

Nun sind nach dieser langen Zeit, auch Buchstaben aufgetaucht.

Die Datenbank hat dann angefangen diese abzuschneiden, was Kollisionen verursacht hat.

Somit hat sich das Problem erledigt.

**Comment by danielberlin** [comment]
Wo hast Du denn Buchstaben in der callId, kannst Du ein Beispiel geben? Bei mir sind es "unique alphanumeric identifier", so wie es auch in der README steht.

**Comment by findingmarbles** [comment]
Ich vermute, dass @merlink01 die Calls per Click2Dial über die XML-RPC API auslöst? Dann verwenden wir in sipgate.io nämlich die XML-RPC session_id weiter, damit man Calls über den API-Wechsel hinaus matchen kann. 
Ich guck mal, ob sich das in der Doku irgendwo gut ergänzen lässt.

**Comment by merlink01** [comment]
Ja, das stimmt. :-)
