### ISSUE TITLE
Request bei Nicht-Erreichen

### ISSUE THREAD

**Issue by BastianS1986** [sipgate/sipgate.io#91]
Ich habe ja die Möglichkeit, beispielsweise wenn ich ein Gespräch wegdrücke oder nach 30 Sekunden nicht den Anruf beantwortet habe, dass dann die Voicemail rangeht. (Wird ja über das Dashboard gesteuert)

Gibt es die Möglichkeit in sipgate.io auch zu steuern, was nach dieser Zeit passieren soll?

Mir schwebt vor, dass ich wählen kann "nach 30 Sekunden spiele Wave File" oder "nach 30 Sekunden spiele ein DTMF Menü".
Beispielsweise eine Ansage, dass man derzeit nicht erreichbar ist, ohne dass es die Möglichkeit gibt eine Nachricht zu hinterlassen.

Beispielsweise:
```
<Response timelimit="30000">
    <Play>
        <Url>http://example.com/example.wav</Url>
    </Play>
</Response>
```

oder

```
<Response timelimit="30000">
    <Gather onData="http://localhost:3000/dtmf" maxDigits="3" timeout="10000">
        <Play>
            <Url>https://example.com/example.wav</Url>
        </Play>
    </Gather>
</Response>
```

Vielleicht gibt es so eine Möglichkeit schon, die ich nicht kenne, fände ich aber ein sehr sinnvolles Feature.
Falls das bereits möglich ist, würde ich mich über eine kurze Rückmeldung freuen, wie :)

**Comment by danielberlin** [comment]
+1 – hatte ich schon in #82 vorgeschlagen.

**Comment by TheCK** [comment]
Hallo @BastianS1986,

wir haben hier intern nochmal drüber gesprochen und finden die Idee auch gut. Allerdings ist das für uns immer noch eher ein langfristiges Feature.

Wir haben das weiter auf dem Schirm, aber ich werde das Issue hier jetzt erst mal schließen.
