### ISSUE TITLE
Parameter diversion funktioniert bei mir nicht immer

### ISSUE THREAD

**Issue by BastianS1986** [sipgate/sipgate.io#92]
Ich bin mit dem Festnetz bei Unitymedia Business und habe eine dauerhafte Umleitung auf meine Simquadrat Nummer, da ich kein Festnetztelefon mehr habe.

Wenn nun jemand auf der Festnetznummer anruft klingelt das Telefon auch, jedoch wird kein diversion Parameter mit übermittelt.

Liegt das an Unitymedia, weil da einfach keine Umleitungsinformation mit kommt oder ist das ein Bug?

**Comment by danielberlin** [comment]
Ich habe das gerade mit einer Weiterleitung von Vodafone zu Simquadrat getestet: Hier sind `diversion` (ursprünglich gewählte Vodafone-Rufnummer) wie auch `to` korrekt gesetzt.

Es scheint also ein Unitymedia-spezifisches Problem zu sein. Leitest Du auf die Festnetz- oder Mobilnummer von SQ weiter? (Zum Verständnis, kann evtl. hiermit zusammenhängen: https://en.wikipedia.org/wiki/International_telecommunications_routes#Grey_routes)

**Comment by BastianS1986** [comment]
Okay....eben hat auch alles wieder normal bei mir funktioniert.
Keine Ahnung woran das lag; Habe nichts verändert.
Ich schließe das mal hier ;)

@danielberlin Danke für die Info!

**Comment by BastianS1986** [comment]
Ich mach das doch nochmal wieder auf.

Es funktioniert zu etwa 50% habe ich das Gefühl.

Konnte folgende Regel entdecken:
Wenn ich bei mir anrufe und ich höre beim Klingeln den "normalen" Freiton, wie man ihn in Deutschland hört, dann ist der Diversion Parameter mit übermittelt.

Wenn ich jedoch im Hörer beim Klingeln einen Ton ähnlich dem "Sonderwählton" höre, dann ist kein Diversion Parameter mit dabei.

**Comment by BastianS1986** [comment]
Reopen

**Comment by TheCK** [comment]
Hallo @BastianS1986,

Ich würde mich da in meiner Einschätzung erstmal dem anschließen, was @danielberlin schon gesagt hat. Vermutlich hat Unitymedia einfach mehrere Routen um zu uns zu terminieren, und je nachdem welche gerade genutzt wird, geht es oder nicht.

Es wäre super, wenn du uns 2 aktuelle Beispiele mit Datum/Uhrzeit/Rufnummern an karsten@sipgate.io schicken könntest, dann prüfen wir das nochmal auf unserer Seite nach. (1 Beispiel, bei dem es funktioniert hat, 1 wo es nicht nicht ging)

**Comment by danielberlin** [comment]
Rein interessehalber würde ich gerne wissen, auf welche Simquadrat-Rufnummer @BastianS1986 weiterleitet (Festnetz- oder Mobilnummer). Das würde helfen zumindest ansatzweise die Intention von Unitymedia zu verstehen, denn bei der Nutzung von grauen Routen geht es sicherlich um das Einsparen von IC-Gebühren.

**Comment by BastianS1986** [comment]
@TheCK und @danielberlin 
Also ich lasse von einem Festnetz zur Festnetznummer von Simquadrat weiterleiten.

Derzeit konnte ich das Problem via Unitymedia auch nicht reproduzieren. Die Logs gehen leider nicht so weit zurück, dass ich das Problem nochmal finden konnte.
Werde das noch weiter beobachten mit Logging. Sobald ich das reproduziert habe schreibe ich an die oben genannte Mailadresse.

Danke euch schonmal :)

**Comment by CookieCrumb23** [comment]
Dann machen wir das Issue erstmal zu.
