### ISSUE TITLE
Anruf nicht terminiert

### ISSUE THREAD

**Issue by merlink01** [sipgate/sipgate.io#93]
Manchmal kommt es vor das nur ein NewCall ausgeführt wird aber eine Nachricht zur terminierung des Gespräches ausbleibt.

Hier ein Konkretes Beispiel:

Newcall:
ID: 3869287033427575675
Datum: 08.03.2016 16:06:38 	
--> 200 OK

Response:
HTTP/1.1 200 OK
Date: Tue, 08 Mar 2016 15:06:37 GMT
Server: Apache
Keep-Alive: timeout=2, max=200
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: application/xml
<?xml version="1.0" encoding="UTF-8"?><Response onAnswer="https://..." onHangup="https://..." />   (Links hier nicht sichtbar)

Leider ist mit dieser ID-Nummer nichts mehr in sipgateIO Log aufgetaucht.

Somit haben wir eine Anrufleiche im System und jegliche Nutzer die in diesem Anruf angeklingelt wurden, werden von unserem System als besetzt eingestuft.

**Comment by merlink01** [comment]
Der fehler war wohl doch nicht SipgateIO geschuldet, sondern Sipgate ansich.
Der Kunde war eine Stunde in der Warteschlange festgehangen und keines der anzusprechenden Telefone hat geklingelt.

Sowas sollte nicht passieren???

**Comment by CookieCrumb23** [comment]
Da hast du natürlich recht, dass so etwas nicht passieren sollte.
Wir geben das an das entsprechende Team weiter.
Aber dieses issue scheint ja dann erledigt zu sein, deswegen schließe ich es.

**Comment by merlink01** [comment]
OK!
