### ISSUE TITLE
Anrufe ansychron ablehnen

### ISSUE THREAD

**Issue by DaSpors** [sipgate/sipgate.io#95]
Gibt es eine Möglichkeit Anrufe abzulehnen außer in der Response auf den initialen POST request?
Anwendungsfall: 
Das Telefon klingelt (dann ist der POST request schon durch), der Nutzer sieht eine Notification, dort ist ein Button 'Ablehnen' und ein Klick weist den Anruf ab (wenn der z.B. Anrufer nervt).

**Comment by fnordian** [comment]
Leider noch nicht. Es gibt noch keine Möglichkeit, auf einen Anruf Einfluss zu nehmen, außer die synchronen POSTs zu beantworten.

**Comment by bfncs** [comment]
Über unsere REST-API ist es jetzt auch möglich, einen Call zu einem beliebigen Zeitpunkt aufzulegen: https://developer.sipgate.io/v2.0/docs/real-time-call-manipulation#section-how-to-hang-up-a-call
