### ISSUE TITLE
HangupCall wird sporadisch nicht gepostet

### ISSUE THREAD

**Issue by soaTf** [sipgate/sipgate.io#96]
Wir haben aktuell 221 Anrufe in unserer Hotline-Log-Tabelle, die von sipgate.io nicht mittels der bereitgestellten OnHangup-Methode terminiert wurden (Zeitraum 07/2015 bis heute). Diese werden zur Zeit manuell bereinigt, indem wir regelmäßig prüfen ob die in unserem Live-Monitor aufgelisteten Telefonate auch tatsächlich geführt werden.
Im Sipgeate.io-Log tauchen keine Fehler diesbezüglich auf.
Wie können wir diesem Problem auf die Schliche kommen? 
Vielen Dank!

**Comment by CookieCrumb23** [comment]
Entschuldigung für die späte Antwort.
Bitte einmal einmal ein paar möglichst aktuelle Beispiele bei denen keine Hangups gepusht wurden mit Datum, Uhrzeit, to- und from-Nummern und CallId an daniel@sipgate.io schicken, dann schauen wir uns das an.
