### ISSUE TITLE
Leerzeichen vor URL

### ISSUE THREAD

**Issue by DaSpors** [sipgate/sipgate.io#97]
Wenn man nicht aufpasst und vor der URL (in den sipgate Einstellungen) ein Leerzeichen hat,
dann gibt es ganz komische HTTP Fehler (Code 610) die es eigentlich nicht gibt.

Anregung: trim(url) oder zumindest trimleft(url)

**Comment by CookieCrumb23** [comment]
Hallo @DaSpors ,

entschuldige die späte Antwort. Dafür haben wir deine Anregung aufgenommen und Leerzeichen vor und nach der URL sollten jetzt keine Probleme mehr bereiten.
Mit den 600ern hast du natürlich auch recht, die haben wir implementiert, um besser debuggen und bei Fehlerfällen helfen zu können.
