### ISSUE TITLE
To which npm user name can I surrender the "sipgate" package on npm?

### ISSUE THREAD

**Issue by philkunz** [sipgate/sipgate.io#99]
Hi, I'm now going to write a sipgate package in the next days that simplifies sipgate.io usage in node. However since there have been some issues regarding trademark names on npm in recent history, I feel more comfortable to take another name that is not in any way trademark protected.

Please let me know to which npm user name I can surrender the "sipgate" packagename.

Thank you!

**Comment by philkunz** [comment]
new package with safe name: https://www.npmjs.com/package/phoneserve

**Comment by TheCK** [comment]
Hi @philkunz,

thanks for your contribution and sorry for the long response time.

please give the package name to the user sipgate. https://www.npmjs.com/~sipgate

Thank you

**Comment by philkunz** [comment]
done!
